// Generated from crates/server-protocol/src/methods.rs; pinned Paseo 2c8e8a8.
// Verify with scripts/check-paseo-client-methods.py; response aliases are adapter-owned.
export interface MethodSpec {
    method: string;
    kind: "request" | "event" | "response";
    channel: number;
    response: string | null;
}

export const METHODS: Readonly<Record<string, MethodSpec>> = {
    "daemon.get_status.request": {
        method: "daemon.get_status.request",
        kind: "request",
        channel: 1,
        response: "daemon.get_status.response",
    },
    "daemon.get_pairing_offer.request": {
        method: "daemon.get_pairing_offer.request",
        kind: "request",
        channel: 1,
        response: "daemon.get_pairing_offer.response",
    },
    "daemon.config.reload.request": {
        method: "daemon.config.reload.request",
        kind: "request",
        channel: 1,
        response: "daemon.config.reload.response",
    },
    "daemon.update.request": {
        method: "daemon.update.request",
        kind: "request",
        channel: 1,
        response: "daemon.update.response",
    },
    "diagnostics.request": {
        method: "diagnostics.request",
        kind: "request",
        channel: 1,
        response: "diagnostics.response",
    },
    get_daemon_config_request: {
        method: "daemon.config.get.request",
        kind: "request",
        channel: 1,
        response: "get_daemon_config_response",
    },
    set_daemon_config_request: {
        method: "daemon.config.set.request",
        kind: "request",
        channel: 1,
        response: "set_daemon_config_response",
    },
    restart_server_request: {
        method: "server.restart.request",
        kind: "request",
        channel: 1,
        response: "status:restart_requested",
    },
    shutdown_server_request: {
        method: "server.shutdown.request",
        kind: "request",
        channel: 1,
        response: "status:shutdown_requested",
    },
    "project.list.request": {
        method: "project.list.request",
        kind: "request",
        channel: 1,
        response: "project.list.response",
    },
    "project.add.request": {
        method: "project.add.request",
        kind: "request",
        channel: 1,
        response: "project.add.response",
    },
    "project.create_directory.request": {
        method: "project.create_directory.request",
        kind: "request",
        channel: 1,
        response: "project.create_directory.response",
    },
    "project.github.clone.request": {
        method: "project.github.clone.request",
        kind: "request",
        channel: 1,
        response: "project.github.clone.response",
    },
    "project.rename.request": {
        method: "project.rename.request",
        kind: "request",
        channel: 1,
        response: "project.rename.response",
    },
    "project.remove.request": {
        method: "project.remove.request",
        kind: "request",
        channel: 1,
        response: "project.remove.response",
    },
    "project.icon.set.request": {
        method: "project.icon.set.request",
        kind: "request",
        channel: 1,
        response: "project.icon.set.response",
    },
    "project.icon.get.request": {
        method: "project.icon.get.request",
        kind: "request",
        channel: 1,
        response: "project.icon.get.response",
    },
    project_icon_request: {
        method: "project.icon.get.request",
        kind: "request",
        channel: 1,
        response: "project_icon_response",
    },
    read_project_config_request: {
        method: "project.config.read.request",
        kind: "request",
        channel: 1,
        response: "read_project_config_response",
    },
    write_project_config_request: {
        method: "project.config.write.request",
        kind: "request",
        channel: 1,
        response: "write_project_config_response",
    },
    fetch_workspaces_request: {
        method: "workspace.list.request",
        kind: "request",
        channel: 1,
        response: "fetch_workspaces_response",
    },
    open_project_request: {
        method: "workspace.open.request",
        kind: "request",
        channel: 1,
        response: "open_project_response",
    },
    "workspace.create.request": {
        method: "workspace.create.request",
        kind: "request",
        channel: 1,
        response: "workspace.create.response",
    },
    archive_workspace_request: {
        method: "workspace.archive.request",
        kind: "request",
        channel: 1,
        response: "archive_workspace_response",
    },
    "workspace.title.set.request": {
        method: "workspace.title.set.request",
        kind: "request",
        channel: 1,
        response: "workspace.title.set.response",
    },
    "workspace.pin.set.request": {
        method: "workspace.pin.set.request",
        kind: "request",
        channel: 1,
        response: "workspace.pin.set.response",
    },
    "workspace.clear_attention.request": {
        method: "workspace.clear_attention.request",
        kind: "request",
        channel: 1,
        response: "workspace.clear_attention.response",
    },
    "workspace.mark_unread.request": {
        method: "workspace.mark_unread.request",
        kind: "request",
        channel: 1,
        response: "workspace.mark_unread.response",
    },
    "workspace.recovery.inspect.request": {
        method: "workspace.recovery.inspect.request",
        kind: "request",
        channel: 1,
        response: "workspace.recovery.inspect.response",
    },
    "workspace.recovery.restore.request": {
        method: "workspace.recovery.restore.request",
        kind: "request",
        channel: 1,
        response: "workspace.recovery.restore.response",
    },
    "workspace.github.search_repositories.request": {
        method: "workspace.github.search_repositories.request",
        kind: "request",
        channel: 1,
        response: "workspace.github.search_repositories.response",
    },
    "workspace.label.list.request": {
        method: "workspace.label.list.request",
        kind: "request",
        channel: 1,
        response: "workspace.label.list.response",
    },
    "workspace.label.assignment.set.request": {
        method: "workspace.label.assignment.set.request",
        kind: "request",
        channel: 1,
        response: "workspace.label.assignment.set.response",
    },
    "workspace.label.update.request": {
        method: "workspace.label.update.request",
        kind: "request",
        channel: 1,
        response: "workspace.label.update.response",
    },
    "workspace.label.delete.inspect.request": {
        method: "workspace.label.delete.inspect.request",
        kind: "request",
        channel: 1,
        response: "workspace.label.delete.inspect.response",
    },
    "workspace.label.delete.request": {
        method: "workspace.label.delete.request",
        kind: "request",
        channel: 1,
        response: "workspace.label.delete.response",
    },
    paseo_worktree_list_request: {
        method: "workspace.worktree.list.request",
        kind: "request",
        channel: 1,
        response: "paseo_worktree_list_response",
    },
    create_paseo_worktree_request: {
        method: "workspace.worktree.create.request",
        kind: "request",
        channel: 1,
        response: "create_paseo_worktree_response",
    },
    paseo_worktree_archive_request: {
        method: "workspace.worktree.archive.request",
        kind: "request",
        channel: 1,
        response: "paseo_worktree_archive_response",
    },
    workspace_setup_status_request: {
        method: "workspace.setup.status.request",
        kind: "request",
        channel: 1,
        response: "workspace_setup_status_response",
    },
    "workspace.setup.run.request": {
        method: "workspace.setup.run.request",
        kind: "request",
        channel: 1,
        response: "workspace.setup.run.response",
    },
    "workspace.script.list.request": {
        method: "workspace.script.list.request",
        kind: "request",
        channel: 1,
        response: "workspace.script.list.response",
    },
    "workspace.script.start.request": {
        method: "workspace.script.start.request",
        kind: "request",
        channel: 1,
        response: "workspace.script.start.response",
    },
    "workspace.script.stop.request": {
        method: "workspace.script.stop.request",
        kind: "request",
        channel: 1,
        response: "workspace.script.stop.response",
    },
    start_workspace_script_request: {
        method: "workspace.script.start.request",
        kind: "request",
        channel: 1,
        response: "start_workspace_script_response",
    },
    fetch_agents_request: {
        method: "agent.list.request",
        kind: "request",
        channel: 0,
        response: "fetch_agents_response",
    },
    fetch_agent_request: {
        method: "agent.get.request",
        kind: "request",
        channel: 0,
        response: "fetch_agent_response",
    },
    fetch_agent_history_request: {
        method: "agent.history.get.request",
        kind: "request",
        channel: 0,
        response: "fetch_agent_history_response",
    },
    "agent.create.request": {
        method: "agent.create.request",
        kind: "request",
        channel: 0,
        response: "agent.create.response",
    },
    create_agent_request: {
        method: "agent.create.request",
        kind: "request",
        channel: 0,
        response: "status:agent_created",
    },
    resume_agent_request: {
        method: "agent.resume.request",
        kind: "request",
        channel: 0,
        response: "status:agent_resumed",
    },
    import_agent_request: {
        method: "agent.import.request",
        kind: "request",
        channel: 0,
        response: "status:agent_resumed",
    },
    refresh_agent_request: {
        method: "agent.refresh.request",
        kind: "request",
        channel: 0,
        response: "status:agent_refreshed",
    },
    update_agent_request: {
        method: "agent.update.request",
        kind: "request",
        channel: 0,
        response: "update_agent_response",
    },
    send_agent_message_request: {
        method: "agent.message.send.request",
        kind: "request",
        channel: 0,
        response: "send_agent_message_response",
    },
    wait_for_finish_request: {
        method: "agent.finish.wait.request",
        kind: "request",
        channel: 0,
        response: "wait_for_finish_response",
    },
    cancel_agent_request: {
        method: "agent.cancel.request",
        kind: "request",
        channel: 0,
        response: "cancel_agent_response",
    },
    archive_agent_request: {
        method: "agent.archive.request",
        kind: "request",
        channel: 0,
        response: "agent_archived",
    },
    delete_agent_request: {
        method: "agent.delete.request",
        kind: "request",
        channel: 0,
        response: "agent_deleted",
    },
    "agent.detach.request": {
        method: "agent.detach.request",
        kind: "request",
        channel: 0,
        response: "agent.detach.response",
    },
    "agent.rewind.request": {
        method: "agent.rewind.request",
        kind: "request",
        channel: 0,
        response: "agent.rewind.response",
    },
    clear_agent_attention: {
        method: "agent.attention.clear.request",
        kind: "request",
        channel: 0,
        response: null,
    },
    close_items_request: {
        method: "agent.items.close.request",
        kind: "request",
        channel: 0,
        response: "close_items_response",
    },
    list_commands_request: {
        method: "agent.commands.list.request",
        kind: "request",
        channel: 0,
        response: "list_commands_response",
    },
    set_agent_mode_request: {
        method: "agent.mode.set.request",
        kind: "request",
        channel: 0,
        response: "set_agent_mode_response",
    },
    set_agent_model_request: {
        method: "agent.model.set.request",
        kind: "request",
        channel: 0,
        response: "set_agent_model_response",
    },
    set_agent_thinking_request: {
        method: "agent.thinking.set.request",
        kind: "request",
        channel: 0,
        response: "set_agent_thinking_response",
    },
    set_agent_feature_request: {
        method: "agent.feature.set.request",
        kind: "request",
        channel: 0,
        response: "set_agent_feature_response",
    },
    "agent.config.apply.request": {
        method: "agent.config.apply.request",
        kind: "request",
        channel: 0,
        response: "agent.config.apply.response",
    },
    agent_permission_response: {
        method: "agent.permission.resolve.request",
        kind: "request",
        channel: 0,
        response: null,
    },
    fetch_agent_timeline_request: {
        method: "agent.timeline.get.request",
        kind: "request",
        channel: 0,
        response: "fetch_agent_timeline_response",
    },
    "agent.timeline.search.request": {
        method: "agent.timeline.search.request",
        kind: "request",
        channel: 0,
        response: "agent.timeline.search.response",
    },
    "agent.timeline.list_prompts.request": {
        method: "agent.timeline.list_prompts.request",
        kind: "request",
        channel: 0,
        response: "agent.timeline.list_prompts.response",
    },
    "agent.timeline.append.request": {
        method: "agent.timeline.append.request",
        kind: "request",
        channel: 0,
        response: "agent.timeline.append.response",
    },
    "agent.timeline.set_subscription.request": {
        method: "agent.timeline.set_subscription.request",
        kind: "request",
        channel: 0,
        response: "agent.timeline.set_subscription.response",
    },
    "agent.fork_context.request": {
        method: "agent.fork_context.request",
        kind: "request",
        channel: 0,
        response: "agent.fork_context.response",
    },
    "agent.provider_subagents.list.request": {
        method: "agent.provider_subagents.list.request",
        kind: "request",
        channel: 0,
        response: "agent.provider_subagents.list.response",
    },
    "agent.provider_subagents.timeline.get.request": {
        method: "agent.provider_subagents.timeline.get.request",
        kind: "request",
        channel: 0,
        response: "agent.provider_subagents.timeline.get.response",
    },
    list_available_providers_request: {
        method: "provider.available.list.request",
        kind: "request",
        channel: 0,
        response: "list_available_providers_response",
    },
    list_provider_models_request: {
        method: "provider.models.list.request",
        kind: "request",
        channel: 0,
        response: "list_provider_models_response",
    },
    list_provider_modes_request: {
        method: "provider.modes.list.request",
        kind: "request",
        channel: 0,
        response: "list_provider_modes_response",
    },
    list_provider_features_request: {
        method: "provider.features.list.request",
        kind: "request",
        channel: 0,
        response: "list_provider_features_response",
    },
    get_providers_snapshot_request: {
        method: "provider.snapshot.get.request",
        kind: "request",
        channel: 0,
        response: "get_providers_snapshot_response",
    },
    refresh_providers_snapshot_request: {
        method: "provider.snapshot.refresh.request",
        kind: "request",
        channel: 0,
        response: "refresh_providers_snapshot_response",
    },
    provider_diagnostic_request: {
        method: "provider.diagnostic.request",
        kind: "request",
        channel: 0,
        response: "provider_diagnostic_response",
    },
    "provider.usage.list.request": {
        method: "provider.usage.list.request",
        kind: "request",
        channel: 0,
        response: "provider.usage.list.response",
    },
    fetch_recent_provider_sessions_request: {
        method: "provider.sessions.recent.list.request",
        kind: "request",
        channel: 0,
        response: "fetch_recent_provider_sessions_response",
    },
    "agent.skills.get_status.request": {
        method: "agent.skills.get_status.request",
        kind: "request",
        channel: 0,
        response: "agent.skills.get_status.response",
    },
    "agent.skills.reconcile.request": {
        method: "agent.skills.reconcile.request",
        kind: "request",
        channel: 0,
        response: "agent.skills.reconcile.response",
    },
    "agent.skills.uninstall.request": {
        method: "agent.skills.uninstall.request",
        kind: "request",
        channel: 0,
        response: "agent.skills.uninstall.response",
    },
    "agent.skills.save_selection.request": {
        method: "agent.skills.save_selection.request",
        kind: "request",
        channel: 0,
        response: "agent.skills.save_selection.response",
    },
    "agent.skills.import_legacy_selection.request": {
        method: "agent.skills.import_legacy_selection.request",
        kind: "request",
        channel: 0,
        response: "agent.skills.import_legacy_selection.response",
    },
    checkout_status_request: {
        method: "checkout.status.get.request",
        kind: "request",
        channel: 2,
        response: "checkout_status_response",
    },
    "checkout.refresh.request": {
        method: "checkout.refresh.request",
        kind: "request",
        channel: 2,
        response: "checkout.refresh.response",
    },
    "checkout.diff.get.request": {
        method: "checkout.diff.get.request",
        kind: "request",
        channel: 2,
        response: "checkout.diff.get.response",
    },
    subscribe_checkout_diff_request: {
        method: "checkout.diff.subscribe.request",
        kind: "request",
        channel: 2,
        response: "subscribe_checkout_diff_response",
    },
    unsubscribe_checkout_diff_request: {
        method: "checkout.diff.unsubscribe.request",
        kind: "request",
        channel: 2,
        response: null,
    },
    "checkout.commits.list.request": {
        method: "checkout.commits.list.request",
        kind: "request",
        channel: 2,
        response: "checkout.commits.list.response",
    },
    "checkout.commits.file_diff.request": {
        method: "checkout.commits.file_diff.request",
        kind: "request",
        channel: 2,
        response: "checkout.commits.file_diff.response",
    },
    validate_branch_request: {
        method: "checkout.branch.validate.request",
        kind: "request",
        channel: 2,
        response: "validate_branch_response",
    },
    branch_suggestions_request: {
        method: "checkout.branch.suggestions.request",
        kind: "request",
        channel: 2,
        response: "branch_suggestions_response",
    },
    checkout_switch_branch_request: {
        method: "checkout.branch.switch.request",
        kind: "request",
        channel: 2,
        response: "checkout_switch_branch_response",
    },
    "checkout.rename_branch.request": {
        method: "checkout.rename_branch.request",
        kind: "request",
        channel: 2,
        response: "checkout.rename_branch.response",
    },
    checkout_commit_request: {
        method: "checkout.commit.request",
        kind: "request",
        channel: 2,
        response: "checkout_commit_response",
    },
    checkout_merge_request: {
        method: "checkout.merge.request",
        kind: "request",
        channel: 2,
        response: "checkout_merge_response",
    },
    checkout_merge_from_base_request: {
        method: "checkout.merge_from_base.request",
        kind: "request",
        channel: 2,
        response: "checkout_merge_from_base_response",
    },
    checkout_pull_request: {
        method: "checkout.pull.request",
        kind: "request",
        channel: 2,
        response: "checkout_pull_response",
    },
    checkout_push_request: {
        method: "checkout.push.request",
        kind: "request",
        channel: 2,
        response: "checkout_push_response",
    },
    "checkout.discard_changes.request": {
        method: "checkout.discard_changes.request",
        kind: "request",
        channel: 2,
        response: "checkout.discard_changes.response",
    },
    stash_save_request: {
        method: "checkout.stash.save.request",
        kind: "request",
        channel: 2,
        response: "stash_save_response",
    },
    stash_pop_request: {
        method: "checkout.stash.pop.request",
        kind: "request",
        channel: 2,
        response: "stash_pop_response",
    },
    stash_list_request: {
        method: "checkout.stash.list.request",
        kind: "request",
        channel: 2,
        response: "stash_list_response",
    },
    "forge.search.request": {
        method: "forge.search.request",
        kind: "request",
        channel: 2,
        response: "forge.search.response",
    },
    github_search_request: {
        method: "github.search.request",
        kind: "request",
        channel: 2,
        response: "github_search_response",
    },
    checkout_pr_create_request: {
        method: "checkout.pr.create.request",
        kind: "request",
        channel: 2,
        response: "checkout_pr_create_response",
    },
    checkout_pr_merge_request: {
        method: "checkout.pr.merge.request",
        kind: "request",
        channel: 2,
        response: "checkout_pr_merge_response",
    },
    checkout_pr_status_request: {
        method: "checkout.pr.status.request",
        kind: "request",
        channel: 2,
        response: "checkout_pr_status_response",
    },
    pull_request_timeline_request: {
        method: "checkout.pr.timeline.request",
        kind: "request",
        channel: 2,
        response: "pull_request_timeline_response",
    },
    "checkout.forge.set_auto_merge.request": {
        method: "checkout.forge.set_auto_merge.request",
        kind: "request",
        channel: 2,
        response: "checkout.forge.set_auto_merge.response",
    },
    "checkout.forge.get_check_details.request": {
        method: "checkout.forge.get_check_details.request",
        kind: "request",
        channel: 2,
        response: "checkout.forge.get_check_details.response",
    },
    "checkout.github.set_auto_merge.request": {
        method: "checkout.github.set_auto_merge.request",
        kind: "request",
        channel: 2,
        response: "checkout.github.set_auto_merge.response",
    },
    "checkout.github.get_check_details.request": {
        method: "checkout.github.get_check_details.request",
        kind: "request",
        channel: 2,
        response: "checkout.github.get_check_details.response",
    },
    directory_suggestions_request: {
        method: "directory.suggestions.request",
        kind: "request",
        channel: 2,
        response: "directory_suggestions_response",
    },
    file_explorer_request: {
        method: "fs.explorer.request",
        kind: "request",
        channel: 2,
        response: "file_explorer_response",
    },
    "fs.file.subscribe.request": {
        method: "fs.file.subscribe.request",
        kind: "request",
        channel: 2,
        response: "fs.file.subscribe.response",
    },
    "fs.file.unsubscribe.request": {
        method: "fs.file.unsubscribe.request",
        kind: "request",
        channel: 2,
        response: "fs.file.unsubscribe.response",
    },
    "fs.file.write.request": {
        method: "fs.file.write.request",
        kind: "request",
        channel: 2,
        response: "fs.file.write.response",
    },
    "fs.entry.create.request": {
        method: "fs.entry.create.request",
        kind: "request",
        channel: 2,
        response: "fs.entry.create.response",
    },
    "fs.entry.rename.request": {
        method: "fs.entry.rename.request",
        kind: "request",
        channel: 2,
        response: "fs.entry.rename.response",
    },
    "fs.entry.duplicate.request": {
        method: "fs.entry.duplicate.request",
        kind: "request",
        channel: 2,
        response: "fs.entry.duplicate.response",
    },
    "fs.entry.delete.request": {
        method: "fs.entry.delete.request",
        kind: "request",
        channel: 2,
        response: "fs.entry.delete.response",
    },
    file_download_token_request: {
        method: "fs.file.download_token.request",
        kind: "request",
        channel: 2,
        response: "file_download_token_response",
    },
    "file.upload.request": {
        method: "file.upload.request",
        kind: "request",
        channel: 2,
        response: "file.upload.response",
    },
    list_terminals_request: {
        method: "terminal.list.request",
        kind: "request",
        channel: 1,
        response: "list_terminals_response",
    },
    subscribe_terminals_request: {
        method: "terminal.list.subscribe.request",
        kind: "request",
        channel: 1,
        response: "list_terminals_response",
    },
    unsubscribe_terminals_request: {
        method: "terminal.list.unsubscribe.request",
        kind: "request",
        channel: 1,
        response: null,
    },
    create_terminal_request: {
        method: "terminal.create.request",
        kind: "request",
        channel: 1,
        response: "create_terminal_response",
    },
    "terminal.rename.request": {
        method: "terminal.rename.request",
        kind: "request",
        channel: 1,
        response: "terminal.rename.response",
    },
    subscribe_terminal_request: {
        method: "terminal.subscribe.request",
        kind: "request",
        channel: 1,
        response: "subscribe_terminal_response",
    },
    unsubscribe_terminal_request: {
        method: "terminal.unsubscribe.request",
        kind: "request",
        channel: 1,
        response: null,
    },
    terminal_input: {
        method: "terminal.input",
        kind: "event",
        channel: 1,
        response: null,
    },
    kill_terminal_request: {
        method: "terminal.kill.request",
        kind: "request",
        channel: 1,
        response: "kill_terminal_response",
    },
    capture_terminal_request: {
        method: "terminal.capture.request",
        kind: "request",
        channel: 1,
        response: "capture_terminal_response",
    },
    "schedule/create": {
        method: "schedule.create.request",
        kind: "request",
        channel: 3,
        response: "schedule/create/response",
    },
    "schedule/list": {
        method: "schedule.list.request",
        kind: "request",
        channel: 3,
        response: "schedule/list/response",
    },
    "schedule/inspect": {
        method: "schedule.inspect.request",
        kind: "request",
        channel: 3,
        response: "schedule/inspect/response",
    },
    "schedule/logs": {
        method: "schedule.logs.request",
        kind: "request",
        channel: 3,
        response: "schedule/logs/response",
    },
    "schedule/update": {
        method: "schedule.update.request",
        kind: "request",
        channel: 3,
        response: "schedule/update/response",
    },
    "schedule/pause": {
        method: "schedule.pause.request",
        kind: "request",
        channel: 3,
        response: "schedule/pause/response",
    },
    "schedule/resume": {
        method: "schedule.resume.request",
        kind: "request",
        channel: 3,
        response: "schedule/resume/response",
    },
    "schedule/delete": {
        method: "schedule.delete.request",
        kind: "request",
        channel: 3,
        response: "schedule/delete/response",
    },
    "schedule/run-once": {
        method: "schedule.run_once.request",
        kind: "request",
        channel: 3,
        response: "schedule/run-once/response",
    },
    set_voice_mode: {
        method: "voice.mode.set.request",
        kind: "request",
        channel: 0,
        response: "set_voice_mode_response",
    },
    voice_audio_chunk: {
        method: "voice.audio.chunk",
        kind: "event",
        channel: 0,
        response: null,
    },
    abort_request: {
        method: "voice.abort.request",
        kind: "request",
        channel: 0,
        response: null,
    },
    audio_played: {
        method: "voice.audio.played",
        kind: "event",
        channel: 0,
        response: null,
    },
    dictation_stream_start: {
        method: "dictation.stream.start",
        kind: "event",
        channel: 0,
        response: null,
    },
    dictation_stream_chunk: {
        method: "dictation.stream.chunk",
        kind: "event",
        channel: 0,
        response: null,
    },
    dictation_stream_finish: {
        method: "dictation.stream.finish",
        kind: "event",
        channel: 0,
        response: null,
    },
    dictation_stream_cancel: {
        method: "dictation.stream.cancel",
        kind: "event",
        channel: 0,
        response: null,
    },
    "session.events.set_subscription.request": {
        method: "session.events.set_subscription.request",
        kind: "request",
        channel: 0,
        response: "session.events.set_subscription.response",
    },
    "subscription.release.request": {
        method: "subscription.release.request",
        kind: "request",
        channel: 0,
        response: "subscription.release.response",
    },
    "creation.subscribe.request": {
        method: "creation.subscribe.request",
        kind: "request",
        channel: 0,
        response: "creation.subscribe.response",
    },
    client_heartbeat: {
        method: "session.heartbeat",
        kind: "event",
        channel: 0,
        response: null,
    },
    ping: {
        method: "connection.ping",
        kind: "request",
        channel: 0,
        response: "pong",
    },
    register_push_token: {
        method: "push.register",
        kind: "event",
        channel: 0,
        response: null,
    },
    "push.unregister.request": {
        method: "push.unregister.request",
        kind: "request",
        channel: 0,
        response: "push.unregister.response",
    },
    "browser.host.register.request": {
        method: "browser.host.register.request",
        kind: "request",
        channel: 3,
        response: "browser.host.register.response",
    },
    "browser.automation.execute.response": {
        method: "browser.automation.execute.response",
        kind: "response",
        channel: 3,
        response: null,
    },
    list_available_editors_request: {
        method: "editor.available.list.request",
        kind: "request",
        channel: 1,
        response: "list_available_editors_response",
    },
    open_in_editor_request: {
        method: "editor.open.request",
        kind: "request",
        channel: 1,
        response: "open_in_editor_response",
    },
};
