[package]
name = "ait-daemon"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ait-application = { path = "../../crates/application" }
ait-ipc = { path = "../../crates/ipc" }
ait-observability = { path = "../../crates/observability" }
ait-storage-sqlite = { path = "../../crates/storage-sqlite" }

[lints]
workspace = true
