//! Workspace execution and Git commit coverage for the Codex adapter.

use std::{
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
};

use ait_agent_adapters::{
    AdapterError, AgentAdapter, AgentCapabilities, AgentEvent, AgentRunRequest, AgentRunStatus,
    AgentStream, SandboxMode,
    codex::{CodexSessionTitleGenerator, CodexWorkspaceAgent},
};
use ait_ports::{
    SessionTitleGenerator, SessionTitleRequest, WorkspaceAgent, WorkspaceAgentInvocation,
    WorkspaceIntegrationCheckpoint, WorkspaceIntegrationGate, WorkspaceOutputItem,
};
use async_trait::async_trait;
use serde_json::json;
use tempfile::TempDir;
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;

#[derive(Debug)]
struct EditingAdapter;

#[async_trait]
impl AgentAdapter for EditingAdapter {
    fn driver(&self) -> &'static str {
        "editing_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        assert_eq!(
            request.project_instructions.as_deref(),
            Some("Keep generated files small.")
        );
        std::fs::write(request.cwd.join("answer.txt"), "generated by codex\n").unwrap();
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemStarted {
                item: json!({
                    "type": "agentMessage",
                    "id": "commentary-1",
                    "phase": "commentary",
                    "text": ""
                }),
            }),
            Ok(AgentEvent::MessageDelta {
                item_id: "commentary-1".into(),
                delta: "Inspecting the ".into(),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "commentary-1",
                    "phase": "commentary",
                    "text": "Inspecting the repository."
                }),
            }),
            Ok(AgentEvent::ItemStarted {
                item: json!({
                    "type": "commandExecution",
                    "id": "command-1",
                    "status": "inProgress"
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "commandExecution",
                    "id": "command-1",
                    "command": "sed -n '1,20p' src/main.rs",
                    "cwd": "/workspace",
                    "status": "completed",
                    "commandActions": [{
                        "type": "read",
                        "command": "sed -n '1,20p' src/main.rs",
                        "name": "main.rs",
                        "path": "src/main.rs"
                    }],
                    "aggregatedOutput": "fn main() {}",
                    "exitCode": 0
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "commentary-2",
                    "phase": "commentary",
                    "text": "The relevant file is small."
                }),
            }),
            Ok(AgentEvent::ItemStarted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-1",
                    "phase": "final_answer",
                    "text": ""
                }),
            }),
            Ok(AgentEvent::MessageDelta {
                item_id: "final-1".into(),
                delta: "Implemented the requested ".into(),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-1",
                    "phase": "final_answer",
                    "text": "Implemented the requested change."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-1".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[derive(Debug)]
struct PausingEditingAdapter {
    entered: Semaphore,
    release: Semaphore,
}

#[derive(Clone, Copy, Debug)]
enum FinalValidationInjection {
    Branch,
    Staged,
    Unstaged,
    Untracked,
}

#[derive(Debug)]
struct InjectingIntegrationGate {
    project: PathBuf,
    injection: FinalValidationInjection,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum TransactionInjection {
    StagedBeforeIndexLock,
    UntrackedAfterWorktreeUpdate,
    SamePathAfterWorktreeUpdate,
    BranchSwitchAfterRefPublish,
    TargetSymrefAfterRefPublish,
    RefConfirmationFailure,
    FailureAfterRefPublish,
    UntrackedBeforeIndexPublish,
    IgnoredBeforeWorktreeMutation,
    SamePathBeforeRollback,
    DirectoryBeforeRollback,
    BaselineRefAdvanceBeforeLock,
}

#[derive(Debug)]
struct TransactionInjectingGate {
    project: PathBuf,
    injection: TransactionInjection,
}

impl TransactionInjectingGate {
    fn switch_branch_after_publication(&self) {
        let candidate = git_output(&self.project, &["rev-parse", "HEAD"]);
        let baseline = git_output(&self.project, &["rev-parse", &format!("{candidate}^")]);
        assert_git_success(
            &self.project,
            &[
                "update-ref",
                "refs/heads/injected-after-publication",
                &baseline,
            ],
        );
        assert_git_success(
            &self.project,
            &[
                "symbolic-ref",
                "HEAD",
                "refs/heads/injected-after-publication",
            ],
        );
        std::fs::write(
            self.project.join("tracked.txt"),
            "external branch-switch value\n",
        )
        .unwrap();
    }

    fn replace_target_with_symref(&self) {
        let target_ref = git_output(&self.project, &["symbolic-ref", "HEAD"]);
        let candidate = head(&self.project);
        assert_git_success(
            &self.project,
            &["update-ref", "refs/heads/injected-ref-target", &candidate],
        );
        assert_git_success(
            &self.project,
            &[
                "symbolic-ref",
                &target_ref,
                "refs/heads/injected-ref-target",
            ],
        );
    }

    fn advance_baseline_ref(&self) {
        let target_ref = git_output(&self.project, &["symbolic-ref", "HEAD"]);
        let current = head(&self.project);
        let replacement = git_output(&self.project, &["rev-parse", &format!("{current}^")]);
        assert_git_success(
            &self.project,
            &[
                "update-ref",
                "--no-deref",
                &target_ref,
                &replacement,
                &current,
            ],
        );
    }

    fn injected_failure(message: &str) -> Result<(), ait_domain::DomainError> {
        Err(ait_domain::DomainError::transient(
            ait_domain::ErrorCode::ProjectGitHeadUnavailable,
            message,
        ))
    }

    fn inject(
        &self,
        checkpoint: WorkspaceIntegrationCheckpoint,
    ) -> Result<(), ait_domain::DomainError> {
        match self.injection {
            TransactionInjection::StagedBeforeIndexLock => {
                std::fs::write(
                    self.project.join("external-staged.txt"),
                    "external staged\n",
                )
                .unwrap();
                assert_git_success(&self.project, &["add", "external-staged.txt"]);
            }
            TransactionInjection::UntrackedAfterWorktreeUpdate
            | TransactionInjection::UntrackedBeforeIndexPublish => {
                std::fs::write(
                    self.project.join("external-untracked.txt"),
                    "external untracked\n",
                )
                .unwrap();
            }
            TransactionInjection::SamePathAfterWorktreeUpdate => {
                std::fs::write(
                    self.project.join("tracked.txt"),
                    "external same-path value\n",
                )
                .unwrap();
            }
            TransactionInjection::BranchSwitchAfterRefPublish => {
                self.switch_branch_after_publication();
            }
            TransactionInjection::TargetSymrefAfterRefPublish => {
                self.replace_target_with_symref();
            }
            TransactionInjection::RefConfirmationFailure => {
                return Self::injected_failure("injected ref confirmation read failure");
            }
            TransactionInjection::FailureAfterRefPublish => {
                return Self::injected_failure("injected ref publication failure");
            }
            TransactionInjection::IgnoredBeforeWorktreeMutation => {
                let path = if self.project.join("shape").is_dir() {
                    self.project.join("shape/ignored.bin")
                } else {
                    self.project.join("generated.txt")
                };
                std::fs::write(path, b"external ignored race\0with bytes\n").unwrap();
            }
            TransactionInjection::SamePathBeforeRollback
                if checkpoint == WorkspaceIntegrationCheckpoint::AfterRefPublish =>
            {
                return Self::injected_failure("injected failure before same-path rollback race");
            }
            TransactionInjection::SamePathBeforeRollback => {
                std::fs::write(
                    self.project.join("tracked.txt"),
                    "external value before rollback isolation\n",
                )
                .unwrap();
            }
            TransactionInjection::DirectoryBeforeRollback
                if checkpoint == WorkspaceIntegrationCheckpoint::AfterRefPublish =>
            {
                return Self::injected_failure("injected failure before directory rollback race");
            }
            TransactionInjection::DirectoryBeforeRollback => {
                std::fs::remove_file(self.project.join("tracked.txt")).unwrap();
                std::fs::create_dir(self.project.join("tracked.txt")).unwrap();
                std::fs::write(
                    self.project.join("tracked.txt/external.bin"),
                    b"external directory race\0with bytes\n",
                )
                .unwrap();
            }
            TransactionInjection::BaselineRefAdvanceBeforeLock => {
                self.advance_baseline_ref();
            }
        }
        Ok(())
    }
}

#[async_trait]
impl WorkspaceIntegrationGate for TransactionInjectingGate {
    async fn begin_integration(&self) -> Result<(), ait_domain::DomainError> {
        Ok(())
    }

    async fn checkpoint(
        &self,
        checkpoint: WorkspaceIntegrationCheckpoint,
    ) -> Result<(), ait_domain::DomainError> {
        let matches = matches!(
            (self.injection, checkpoint),
            (
                TransactionInjection::StagedBeforeIndexLock,
                WorkspaceIntegrationCheckpoint::BeforeIndexLock
            ) | (
                TransactionInjection::UntrackedAfterWorktreeUpdate
                    | TransactionInjection::SamePathAfterWorktreeUpdate,
                WorkspaceIntegrationCheckpoint::AfterWorktreeUpdate
            ) | (
                TransactionInjection::RefConfirmationFailure,
                WorkspaceIntegrationCheckpoint::BeforeRefCommitConfirmation
            ) | (
                TransactionInjection::BranchSwitchAfterRefPublish
                    | TransactionInjection::TargetSymrefAfterRefPublish
                    | TransactionInjection::FailureAfterRefPublish,
                WorkspaceIntegrationCheckpoint::AfterRefPublish
            ) | (
                TransactionInjection::UntrackedBeforeIndexPublish,
                WorkspaceIntegrationCheckpoint::BeforeIndexPublish
            ) | (
                TransactionInjection::IgnoredBeforeWorktreeMutation,
                WorkspaceIntegrationCheckpoint::BeforeWorktreeMutation
            ) | (
                TransactionInjection::SamePathBeforeRollback
                    | TransactionInjection::DirectoryBeforeRollback,
                WorkspaceIntegrationCheckpoint::AfterRefPublish
                    | WorkspaceIntegrationCheckpoint::BeforeWorktreeRollback
            ) | (
                TransactionInjection::BaselineRefAdvanceBeforeLock,
                WorkspaceIntegrationCheckpoint::AfterRefPublish
                    | WorkspaceIntegrationCheckpoint::BeforeBaselineRefReconciliationLock
            )
        );
        if !matches {
            return Ok(());
        }
        self.inject(checkpoint)
    }
}

#[derive(Debug)]
struct TransactionEditingAdapter;

#[derive(Clone, Copy, Debug)]
enum DirectoryFileDirection {
    FileToDirectory,
    DirectoryToFile,
}

#[derive(Debug)]
struct DirectoryFileEditingAdapter {
    direction: DirectoryFileDirection,
}

#[derive(Clone, Copy, Debug)]
enum IgnoredCollisionKind {
    TrackIgnoredFile,
    ReplaceDirectory,
}

#[derive(Debug)]
struct IgnoredCollisionAdapter {
    kind: IgnoredCollisionKind,
}

#[derive(Debug)]
struct AttributeEditingAdapter;

#[async_trait]
impl AgentAdapter for DirectoryFileEditingAdapter {
    fn driver(&self) -> &'static str {
        "directory_file_editing_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        let path = request.cwd.join("shape");
        match self.direction {
            DirectoryFileDirection::FileToDirectory => {
                std::fs::remove_file(&path).unwrap();
                std::fs::create_dir(&path).unwrap();
                std::fs::write(path.join("child.txt"), "Run directory child\n").unwrap();
            }
            DirectoryFileDirection::DirectoryToFile => {
                std::fs::remove_dir_all(&path).unwrap();
                std::fs::write(&path, "Run file value\n").unwrap();
            }
        }
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "directory-file-final",
                    "phase": "final_answer",
                    "text": "Finished D/F edit."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "directory-file-turn".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[async_trait]
impl AgentAdapter for IgnoredCollisionAdapter {
    fn driver(&self) -> &'static str {
        "ignored_collision_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        match self.kind {
            IgnoredCollisionKind::TrackIgnoredFile => {
                std::fs::remove_file(request.cwd.join(".gitignore")).unwrap();
                std::fs::write(request.cwd.join("generated.txt"), "Run value\n").unwrap();
            }
            IgnoredCollisionKind::ReplaceDirectory => {
                std::fs::remove_dir_all(request.cwd.join("shape")).unwrap();
                std::fs::write(request.cwd.join("shape"), "Run file value\n").unwrap();
            }
        }
        Ok(test_completion_stream(
            "ignored-collision-final",
            "Finished ignored collision edit.",
        ))
    }
}

#[async_trait]
impl AgentAdapter for AttributeEditingAdapter {
    fn driver(&self) -> &'static str {
        "attribute_editing_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        std::fs::write(request.cwd.join(".gitattributes"), "data.txt ident\n").unwrap();
        std::fs::write(request.cwd.join("data.txt"), "Run $Id$ value\n").unwrap();
        Ok(test_completion_stream(
            "attribute-final",
            "Finished attribute-sensitive edit.",
        ))
    }
}

fn test_completion_stream(id: &str, text: &str) -> AgentStream {
    Box::pin(tokio_stream::iter([
        Ok(AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": id,
                "phase": "final_answer",
                "text": text
            }),
        }),
        Ok(AgentEvent::Completed {
            turn_id: format!("{id}-turn"),
            status: AgentRunStatus::Completed,
            error: None,
        }),
    ]))
}

#[async_trait]
impl AgentAdapter for TransactionEditingAdapter {
    fn driver(&self) -> &'static str {
        "transaction_editing_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        std::fs::write(request.cwd.join("tracked.txt"), "Run tracked value\n").unwrap();
        std::fs::write(request.cwd.join("run-owned.txt"), "Run owned value\n").unwrap();
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "transaction-final",
                    "phase": "final_answer",
                    "text": "Finished transactional edit."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "transaction-turn".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[async_trait]
impl WorkspaceIntegrationGate for InjectingIntegrationGate {
    async fn begin_integration(&self) -> Result<(), ait_domain::DomainError> {
        match self.injection {
            FinalValidationInjection::Branch => {
                assert!(
                    Command::new("git")
                        .arg("-C")
                        .arg(&self.project)
                        .args(["switch", "injected-branch"])
                        .status()
                        .unwrap()
                        .success()
                );
            }
            FinalValidationInjection::Staged => {
                std::fs::write(self.project.join("staged.txt"), "external staged change\n")
                    .unwrap();
                assert!(
                    Command::new("git")
                        .arg("-C")
                        .arg(&self.project)
                        .args(["add", "staged.txt"])
                        .status()
                        .unwrap()
                        .success()
                );
            }
            FinalValidationInjection::Unstaged => {
                std::fs::write(
                    self.project.join("tracked.txt"),
                    "external unstaged change\n",
                )
                .unwrap();
            }
            FinalValidationInjection::Untracked => {
                std::fs::write(
                    self.project.join("untracked.txt"),
                    "external untracked change\n",
                )
                .unwrap();
            }
        }
        Ok(())
    }
}

#[derive(Debug)]
struct AbsolutePathAdapter;

#[async_trait]
impl AgentAdapter for AbsolutePathAdapter {
    fn driver(&self) -> &'static str {
        "absolute_path_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        let root = request.cwd.display().to_string();
        let answer = request.cwd.join("answer.txt").display().to_string();
        let image = request.cwd.join("preview.png").display().to_string();
        std::fs::write(&answer, "generated\n").unwrap();
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "commandExecution",
                    "id": "absolute-cwd",
                    "status": "completed",
                    "commandActions": [{"type": "listFiles", "cwd": root}]
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "fileChange",
                    "id": "absolute-file",
                    "status": "completed",
                    "changes": [{"path": answer, "kind": "add"}]
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "imageView",
                    "id": "absolute-image",
                    "status": "completed",
                    "path": image
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-paths",
                    "phase": "final_answer",
                    "text": "Recorded paths."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-paths".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

impl PausingEditingAdapter {
    fn new() -> Self {
        Self {
            entered: Semaphore::new(0),
            release: Semaphore::new(0),
        }
    }

    async fn started(&self) {
        self.entered.acquire().await.unwrap().forget();
    }
}

#[async_trait]
impl AgentAdapter for PausingEditingAdapter {
    fn driver(&self) -> &'static str {
        "pausing_editing_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        std::fs::write(request.cwd.join("agent-owned.txt"), "agent change\n").unwrap();
        self.entered.add_permits(1);
        tokio::select! {
            permit = self.release.acquire() => permit.unwrap().forget(),
            () = request.cancellation.cancelled() => return Err(AdapterError::cancelled()),
        }
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-paused",
                    "phase": "final_answer",
                    "text": "Finished isolated edit."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-paused".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[derive(Debug)]
struct TitleAdapter;

#[async_trait]
impl AgentAdapter for TitleAdapter {
    fn driver(&self) -> &'static str {
        "title_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: false,
            file_changes: false,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        assert_eq!(request.model.as_deref(), Some("gpt-5.6-luna"));
        assert_eq!(request.reasoning_effort.as_deref(), Some("low"));
        assert_eq!(request.sandbox, SandboxMode::ReadOnly);
        assert_eq!(
            request.output_schema.as_ref().unwrap()["required"][0],
            "title"
        );
        assert!(request.prompt.contains("ABC-123"));
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::MessageDelta {
                item_id: "message-title".into(),
                delta: r#"{"title":"修复 ABC-123 登录","description":"修复登录流程中的工单问题"}"#
                    .into(),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-title".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[derive(Debug)]
struct ScriptedAdapter {
    events: Vec<AgentEvent>,
}

#[async_trait]
impl AgentAdapter for ScriptedAdapter {
    fn driver(&self) -> &'static str {
        "scripted_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: false,
            file_changes: false,
            usage: false,
        }
    }

    async fn run(&self, _: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        Ok(Box::pin(tokio_stream::iter(
            self.events.clone().into_iter().map(Ok),
        )))
    }
}

fn initialized_project() -> TempDir {
    let project = TempDir::new().unwrap();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .arg("init")
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args([
                "-c",
                "user.name=Test",
                "-c",
                "user.email=test@example.invalid",
                "commit",
                "--allow-empty",
                "-m",
                "initial",
            ])
            .status()
            .unwrap()
            .success()
    );
    project
}

fn head(project: &Path) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .args(["rev-parse", "HEAD"])
        .output()
        .unwrap();
    String::from_utf8(output.stdout).unwrap().trim().to_owned()
}

fn index_tree(project: &Path) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .arg("write-tree")
        .output()
        .unwrap();
    assert!(output.status.success());
    String::from_utf8(output.stdout).unwrap().trim().to_owned()
}

fn git_output(project: &Path, arguments: &[&str]) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .args(arguments)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "git {arguments:?}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).unwrap().trim().to_owned()
}

fn assert_git_success(project: &Path, arguments: &[&str]) {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .args(arguments)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "git {arguments:?}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn commit_all(project: &Path, subject: &str) {
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project)
            .args(["add", "--all"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project)
            .args([
                "-c",
                "user.name=Test",
                "-c",
                "user.email=test@example.invalid",
                "commit",
                "-m",
                subject,
            ])
            .status()
            .unwrap()
            .success()
    );
}

fn run_ref(project: &Path) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .args(["for-each-ref", "--format=%(refname)", "refs/ait/runs"])
        .output()
        .unwrap();
    let references = String::from_utf8(output.stdout).unwrap();
    let references = references.lines().collect::<Vec<_>>();
    assert_eq!(references.len(), 1);
    references[0].to_owned()
}

fn paused_request(project: &Path, request_id: &str) -> WorkspaceAgentInvocation {
    WorkspaceAgentInvocation {
        request_id: request_id.into(),
        model: "test-model".into(),
        reasoning_effort: None,
        prompt: "Make an isolated edit".into(),
        project_instructions: None,
        commit_subject: "Make an isolated edit".into(),
        cwd: project.to_path_buf(),
        baseline_commit: head(project),
        baseline_index_tree: index_tree(project),
        cancellation: CancellationToken::new(),
        integration_gate: None,
    }
}

async fn invoke_script(events: Vec<AgentEvent>) -> ait_ports::WorkspaceAgentResponse {
    let project = initialized_project();
    CodexWorkspaceAgent::new(Arc::new(ScriptedAdapter { events }))
        .invoke(WorkspaceAgentInvocation {
            request_id: "scripted-run".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Return a result".into(),
            project_instructions: None,
            commit_subject: "Return a result".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap()
}

#[tokio::test]
async fn generates_structured_session_metadata_with_the_small_read_only_model() {
    let project = TempDir::new().unwrap();
    let generator = CodexSessionTitleGenerator::new(Arc::new(TitleAdapter));
    let generated = generator
        .generate(SessionTitleRequest {
            request_id: "title-1".into(),
            user_prompt: "修复 ABC-123 登录".into(),
            cwd: project.path().to_path_buf(),
            cancellation: CancellationToken::new(),
        })
        .await
        .unwrap();

    assert_eq!(generated.title, "修复 ABC-123 登录");
    assert_eq!(generated.description, "修复登录流程中的工单问题");
}

#[tokio::test]
async fn returns_assistant_result_and_commits_generated_changes() {
    let project = initialized_project();
    let agent = CodexWorkspaceAgent::new(Arc::new(EditingAdapter));
    let result = agent
        .invoke(WorkspaceAgentInvocation {
            request_id: "run-1".into(),
            model: "test-model".into(),
            reasoning_effort: Some("high".into()),
            prompt: "Create answer.txt".into(),
            project_instructions: Some("Keep generated files small.".into()),
            commit_subject: "Create the generated answer".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap();

    assert_eq!(result.assistant_text, "Implemented the requested change.");
    assert!(result.commit_id.is_some());
    assert_eq!(result.operations.len(), 1);
    assert_eq!(result.operations[0].kind, "read");
    assert_eq!(result.operations[0].title, "Read file");
    assert_eq!(result.operations[0].paths, ["src/main.rs"]);
    assert!(
        result.operations[0]
            .detail
            .as_deref()
            .unwrap()
            .contains("fn main() {}")
    );
    assert_eq!(
        result.output_items,
        [
            WorkspaceOutputItem::Message {
                id: "commentary-1".into(),
                phase: Some("commentary".into()),
                text: "Inspecting the repository.".into(),
            },
            WorkspaceOutputItem::Operation {
                id: "command-1".into(),
            },
            WorkspaceOutputItem::Message {
                id: "commentary-2".into(),
                phase: Some("commentary".into()),
                text: "The relevant file is small.".into(),
            },
            WorkspaceOutputItem::Message {
                id: "final-1".into(),
                phase: Some("final_answer".into()),
                text: "Implemented the requested change.".into(),
            },
        ]
    );
    let subject = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["log", "-1", "--pretty=%s"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8_lossy(&subject.stdout).trim(),
        "ait: Create the generated answer"
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join("answer.txt")).unwrap(),
        "generated by codex\n"
    );
    let status = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["status", "--porcelain=v1"])
        .output()
        .unwrap();
    assert!(status.stdout.is_empty());
    let worktrees = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["worktree", "list", "--porcelain"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(worktrees.stdout)
            .unwrap()
            .lines()
            .filter(|line| line.starts_with("worktree "))
            .count(),
        1
    );
    let refs = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["for-each-ref", "refs/ait/runs"])
        .output()
        .unwrap();
    assert!(refs.stdout.is_empty());
}

#[tokio::test]
async fn detached_primary_head_advances_without_moving_the_original_branch() {
    let project = initialized_project();
    let branch = git_output(project.path(), &["symbolic-ref", "HEAD"]);
    let baseline = head(project.path());
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args(["checkout", "--detach"])
            .status()
            .unwrap()
            .success()
    );

    let result = CodexWorkspaceAgent::new(Arc::new(EditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "detached-head".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Create answer.txt".into(),
            project_instructions: Some("Keep generated files small.".into()),
            commit_subject: "Create answer.txt".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: baseline.clone(),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap();

    assert_eq!(head(project.path()), result.commit_id.unwrap());
    assert_eq!(
        git_output(project.path(), &["rev-parse", &branch]),
        baseline
    );
    let symbolic = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["symbolic-ref", "--quiet", "HEAD"])
        .status()
        .unwrap();
    assert_eq!(symbolic.code(), Some(1));
}

#[tokio::test]
async fn retains_completed_only_final_text_and_does_not_repeat_completed_delta_text() {
    let completed_only = invoke_script(vec![
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "final-completed-only",
                "phase": "final_answer",
                "text": "Complete final answer."
            }),
        },
        AgentEvent::Completed {
            turn_id: "turn-completed-only".into(),
            status: AgentRunStatus::Completed,
            error: None,
        },
    ])
    .await;
    assert_eq!(completed_only.assistant_text, "Complete final answer.");
    assert_eq!(
        completed_only.output_items,
        [WorkspaceOutputItem::Message {
            id: "final-completed-only".into(),
            phase: Some("final_answer".into()),
            text: "Complete final answer.".into(),
        }]
    );

    let delta_and_completed = invoke_script(vec![
        AgentEvent::MessageDelta {
            item_id: "final-with-delta".into(),
            delta: "Complete ".into(),
        },
        AgentEvent::MessageDelta {
            item_id: "final-with-delta".into(),
            delta: "final answer.".into(),
        },
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "final-with-delta",
                "phase": "final_answer",
                "text": "Complete final answer."
            }),
        },
        AgentEvent::Completed {
            turn_id: "turn-with-delta".into(),
            status: AgentRunStatus::Completed,
            error: None,
        },
    ])
    .await;
    assert_eq!(delta_and_completed.assistant_text, "Complete final answer.");
    assert_eq!(
        delta_and_completed.output_items,
        [WorkspaceOutputItem::Message {
            id: "final-with-delta".into(),
            phase: Some("final_answer".into()),
            text: "Complete final answer.".into(),
        }]
    );
}

#[tokio::test]
async fn keeps_messages_from_legacy_streams_without_phase() {
    let result = invoke_script(vec![
        AgentEvent::MessageDelta {
            item_id: "legacy-progress".into(),
            delta: "Legacy progress".into(),
        },
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "legacy-progress",
                "text": "Legacy progress message."
            }),
        },
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "legacy-final",
                "text": "Legacy final answer."
            }),
        },
        AgentEvent::Completed {
            turn_id: "legacy-turn".into(),
            status: AgentRunStatus::Completed,
            error: None,
        },
    ])
    .await;

    assert_eq!(result.assistant_text, "Legacy final answer.");
    assert_eq!(
        result.output_items,
        [
            WorkspaceOutputItem::Message {
                id: "legacy-progress".into(),
                phase: None,
                text: "Legacy progress message.".into(),
            },
            WorkspaceOutputItem::Message {
                id: "legacy-final".into(),
                phase: None,
                text: "Legacy final answer.".into(),
            },
        ]
    );
}

#[tokio::test]
async fn refuses_to_mix_existing_user_changes_into_codex_commit() {
    let project = initialized_project();
    std::fs::write(project.path().join("user-work.txt"), "keep me\n").unwrap();
    let agent = CodexWorkspaceAgent::new(Arc::new(EditingAdapter));
    let error = agent
        .invoke(WorkspaceAgentInvocation {
            request_id: "run-2".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Change something".into(),
            project_instructions: None,
            commit_subject: "Change something".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap_err();

    assert_eq!(error.code, ait_domain::ErrorCode::ProjectGitDirty);
    assert!(!project.path().join("answer.txt").exists());
}

#[tokio::test]
async fn running_user_edit_is_not_mixed_and_the_agent_commit_is_retained() {
    let project = initialized_project();
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "user-edit-race");
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    assert!(!project.path().join("agent-owned.txt").exists());
    std::fs::write(project.path().join("user-owned.txt"), "user change\n").unwrap();
    adapter.release.add_permits(1);

    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(failure.code, ait_domain::ErrorCode::ProjectGitDirty);
    assert!(
        failure
            .message
            .contains("isolated Run changes were retained")
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join("user-owned.txt")).unwrap(),
        "user change\n"
    );
    assert!(!project.path().join("agent-owned.txt").exists());
    let reference = run_ref(project.path());
    let changed = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["show", "--pretty=format:", "--name-only", &reference])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(changed.stdout).unwrap().trim(),
        "agent-owned.txt"
    );
}

#[tokio::test]
async fn head_advance_rejects_integration_without_overwriting_either_change() {
    let project = initialized_project();
    let baseline = head(project.path());
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "head-race");
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    std::fs::write(project.path().join("external.txt"), "external commit\n").unwrap();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args(["add", "external.txt"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args([
                "-c",
                "user.name=External",
                "-c",
                "user.email=external@example.invalid",
                "commit",
                "-m",
                "external",
            ])
            .status()
            .unwrap()
            .success()
    );
    adapter.release.add_permits(1);

    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(
        failure.code,
        ait_domain::ErrorCode::ProjectGitHeadUnavailable
    );
    assert_ne!(head(project.path()), baseline);
    assert!(!project.path().join("agent-owned.txt").exists());
    let reference = run_ref(project.path());
    let merge_base = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["merge-base", &reference, "HEAD"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(merge_base.stdout).unwrap().trim(),
        baseline
    );
}

#[tokio::test]
async fn index_change_rejects_integration_and_leaves_the_index_intact() {
    let project = initialized_project();
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "index-race");
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    std::fs::write(project.path().join("staged.txt"), "staged user change\n").unwrap();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args(["add", "staged.txt"])
            .status()
            .unwrap()
            .success()
    );
    adapter.release.add_permits(1);

    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(failure.code, ait_domain::ErrorCode::ProjectGitDirty);
    let staged = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["diff", "--cached", "--name-only"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(staged.stdout).unwrap().trim(),
        "staged.txt"
    );
    assert!(!project.path().join("agent-owned.txt").exists());
    let _reference = run_ref(project.path());
}

#[tokio::test]
async fn cancellation_never_integrates_partial_changes_and_blocks_implicit_recovery() {
    let project = initialized_project();
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "cancelled-race");
    let mut retry = request.clone();
    retry.cancellation = CancellationToken::new();
    let cancellation = request.cancellation.clone();
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    cancellation.cancel();
    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(failure.code, ait_domain::ErrorCode::RunCancelled);
    assert!(
        failure
            .message
            .contains("isolated Run changes were retained")
    );
    assert!(!project.path().join("agent-owned.txt").exists());
    let _reference = run_ref(project.path());

    let retried = CodexWorkspaceAgent::new(adapter)
        .invoke(retry)
        .await
        .unwrap_err();
    assert_eq!(retried.code, ait_domain::ErrorCode::RunRecoveryFailed);
}

#[tokio::test]
async fn final_validation_injections_preserve_the_target_ref_and_external_changes() {
    for injection in [
        FinalValidationInjection::Branch,
        FinalValidationInjection::Staged,
        FinalValidationInjection::Unstaged,
        FinalValidationInjection::Untracked,
    ] {
        let project = initialized_project();
        std::fs::write(project.path().join("tracked.txt"), "authorized content\n").unwrap();
        commit_all(project.path(), "add tracked fixture");
        assert!(
            Command::new("git")
                .arg("-C")
                .arg(project.path())
                .args(["branch", "injected-branch"])
                .status()
                .unwrap()
                .success()
        );
        let baseline = head(project.path());
        let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);
        let adapter = Arc::new(PausingEditingAdapter::new());
        let agent = CodexWorkspaceAgent::new(adapter.clone());
        let mut request = paused_request(project.path(), &format!("final-{injection:?}"));
        request.integration_gate = Some(Arc::new(InjectingIntegrationGate {
            project: project.path().to_path_buf(),
            injection,
        }));
        let running = tokio::spawn(async move { agent.invoke(request).await });
        adapter.started().await;
        adapter.release.add_permits(1);

        let failure = running.await.unwrap().unwrap_err();
        let expected = if matches!(injection, FinalValidationInjection::Branch) {
            ait_domain::ErrorCode::ProjectGitHeadUnavailable
        } else {
            ait_domain::ErrorCode::ProjectGitDirty
        };
        assert_eq!(failure.code, expected, "injection: {injection:?}");
        assert_eq!(
            git_output(project.path(), &["rev-parse", &target_ref]),
            baseline,
            "the admitted target ref advanced for {injection:?}"
        );
        assert!(!project.path().join("agent-owned.txt").exists());
        match injection {
            FinalValidationInjection::Branch => {
                assert_eq!(
                    git_output(project.path(), &["symbolic-ref", "--short", "HEAD"]),
                    "injected-branch"
                );
            }
            FinalValidationInjection::Staged => {
                assert_eq!(
                    git_output(project.path(), &["diff", "--cached", "--name-only"]),
                    "staged.txt"
                );
            }
            FinalValidationInjection::Unstaged => {
                assert_eq!(
                    std::fs::read_to_string(project.path().join("tracked.txt")).unwrap(),
                    "external unstaged change\n"
                );
            }
            FinalValidationInjection::Untracked => {
                assert_eq!(
                    std::fs::read_to_string(project.path().join("untracked.txt")).unwrap(),
                    "external untracked change\n"
                );
            }
        }
        let _retained_agent_commit = run_ref(project.path());
    }
}

#[tokio::test]
async fn publication_phase_failures_roll_back_run_changes_and_preserve_external_writes() {
    for injection in [
        TransactionInjection::StagedBeforeIndexLock,
        TransactionInjection::UntrackedAfterWorktreeUpdate,
        TransactionInjection::SamePathAfterWorktreeUpdate,
        TransactionInjection::BranchSwitchAfterRefPublish,
        TransactionInjection::RefConfirmationFailure,
        TransactionInjection::FailureAfterRefPublish,
        TransactionInjection::UntrackedBeforeIndexPublish,
    ] {
        let project = initialized_project();
        std::fs::write(project.path().join("tracked.txt"), "authorized baseline\n").unwrap();
        commit_all(project.path(), "add transaction fixture");
        let baseline = head(project.path());
        let baseline_index = index_tree(project.path());
        let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);
        let failure = CodexWorkspaceAgent::new(Arc::new(TransactionEditingAdapter))
            .invoke(WorkspaceAgentInvocation {
                request_id: format!("transaction-{injection:?}"),
                model: "test-model".into(),
                reasoning_effort: None,
                prompt: "Replace tracked.txt and add run-owned.txt".into(),
                project_instructions: None,
                commit_subject: "Exercise integration rollback".into(),
                cwd: project.path().to_path_buf(),
                baseline_commit: baseline.clone(),
                baseline_index_tree: baseline_index.clone(),
                cancellation: CancellationToken::new(),
                integration_gate: Some(Arc::new(TransactionInjectingGate {
                    project: project.path().to_path_buf(),
                    injection,
                })),
            })
            .await
            .unwrap_err();
        assert_transaction_rollback(
            project.path(),
            injection,
            &failure,
            &baseline,
            &baseline_index,
            &target_ref,
        );
    }
}

fn assert_transaction_rollback(
    project: &Path,
    injection: TransactionInjection,
    failure: &ait_domain::DomainError,
    baseline: &str,
    baseline_index: &str,
    target_ref: &str,
) {
    let expected = if matches!(
        injection,
        TransactionInjection::SamePathAfterWorktreeUpdate
            | TransactionInjection::BranchSwitchAfterRefPublish
    ) {
        ait_domain::ErrorCode::RunRecoveryFailed
    } else if matches!(
        injection,
        TransactionInjection::StagedBeforeIndexLock
            | TransactionInjection::UntrackedAfterWorktreeUpdate
            | TransactionInjection::UntrackedBeforeIndexPublish
    ) {
        ait_domain::ErrorCode::ProjectGitDirty
    } else {
        ait_domain::ErrorCode::ProjectGitHeadUnavailable
    };
    assert_eq!(failure.code, expected, "injection: {injection:?}");
    assert_eq!(
        git_output(project, &["rev-parse", target_ref]),
        baseline,
        "target ref changed for {injection:?}"
    );
    assert!(
        !project.join("run-owned.txt").exists(),
        "Run-owned file leaked for {injection:?}"
    );
    if !matches!(injection, TransactionInjection::StagedBeforeIndexLock) {
        assert_eq!(
            index_tree(project),
            baseline_index,
            "canonical index retained Run state for {injection:?}"
        );
    }

    match injection {
        TransactionInjection::StagedBeforeIndexLock => {
            assert_eq!(
                git_output(project, &["diff", "--cached", "--name-only"]),
                "external-staged.txt"
            );
            assert_eq!(
                std::fs::read_to_string(project.join("external-staged.txt")).unwrap(),
                "external staged\n"
            );
        }
        TransactionInjection::UntrackedAfterWorktreeUpdate
        | TransactionInjection::UntrackedBeforeIndexPublish => {
            assert_eq!(
                std::fs::read_to_string(project.join("external-untracked.txt")).unwrap(),
                "external untracked\n"
            );
            assert_eq!(
                std::fs::read_to_string(project.join("tracked.txt")).unwrap(),
                "authorized baseline\n"
            );
        }
        TransactionInjection::SamePathAfterWorktreeUpdate => assert_eq!(
            std::fs::read_to_string(project.join("tracked.txt")).unwrap(),
            "external same-path value\n"
        ),
        TransactionInjection::BranchSwitchAfterRefPublish => {
            assert_eq!(
                git_output(project, &["symbolic-ref", "HEAD"]),
                "refs/heads/injected-after-publication"
            );
            assert_eq!(head(project), baseline);
            assert_eq!(
                std::fs::read_to_string(project.join("tracked.txt")).unwrap(),
                "external branch-switch value\n"
            );
        }
        TransactionInjection::RefConfirmationFailure
        | TransactionInjection::FailureAfterRefPublish => {
            assert_eq!(
                std::fs::read_to_string(project.join("tracked.txt")).unwrap(),
                "authorized baseline\n"
            );
            assert!(git_output(project, &["status", "--porcelain=v1"]).is_empty());
        }
        TransactionInjection::TargetSymrefAfterRefPublish => {
            unreachable!("the ref-identity injection has dedicated assertions")
        }
        TransactionInjection::IgnoredBeforeWorktreeMutation
        | TransactionInjection::SamePathBeforeRollback
        | TransactionInjection::DirectoryBeforeRollback
        | TransactionInjection::BaselineRefAdvanceBeforeLock => {
            unreachable!("the TOCTOU injections have dedicated assertions")
        }
    }
    let _retained_run_commit = run_ref(project);
}

#[tokio::test]
async fn ignored_files_that_candidate_paths_would_replace_are_rejected_before_mutation() {
    for kind in [
        IgnoredCollisionKind::TrackIgnoredFile,
        IgnoredCollisionKind::ReplaceDirectory,
    ] {
        let project = initialized_project();
        match kind {
            IgnoredCollisionKind::TrackIgnoredFile => {
                std::fs::write(project.path().join(".gitignore"), "generated.txt\n").unwrap();
                commit_all(project.path(), "ignore generated file");
                std::fs::write(
                    project.path().join("generated.txt"),
                    b"external ignored value\0with bytes\n",
                )
                .unwrap();
            }
            IgnoredCollisionKind::ReplaceDirectory => {
                std::fs::write(project.path().join(".gitignore"), "shape/ignored.bin\n").unwrap();
                std::fs::create_dir(project.path().join("shape")).unwrap();
                std::fs::write(
                    project.path().join("shape/tracked.txt"),
                    "baseline tracked child\n",
                )
                .unwrap();
                commit_all(project.path(), "add ignored D/F fixture");
                std::fs::write(
                    project.path().join("shape/ignored.bin"),
                    b"external ignored child\0with bytes\n",
                )
                .unwrap();
            }
        }
        assert!(git_output(project.path(), &["status", "--porcelain=v1"]).is_empty());
        let baseline = head(project.path());
        let baseline_index = index_tree(project.path());
        let baseline_index_bytes = std::fs::read(project.path().join(".git/index")).unwrap();
        let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

        let failure = CodexWorkspaceAgent::new(Arc::new(IgnoredCollisionAdapter { kind }))
            .invoke(WorkspaceAgentInvocation {
                request_id: format!("ignored-collision-{kind:?}"),
                model: "test-model".into(),
                reasoning_effort: None,
                prompt: "Exercise an ignored filesystem collision".into(),
                project_instructions: None,
                commit_subject: "Exercise ignored collision rejection".into(),
                cwd: project.path().to_path_buf(),
                baseline_commit: baseline.clone(),
                baseline_index_tree: baseline_index.clone(),
                cancellation: CancellationToken::new(),
                integration_gate: None,
            })
            .await
            .unwrap_err();

        assert_eq!(
            failure.code,
            ait_domain::ErrorCode::ProjectGitDirty,
            "kind: {kind:?}: {}",
            failure.message
        );
        assert_eq!(
            git_output(project.path(), &["rev-parse", &target_ref]),
            baseline
        );
        assert_eq!(index_tree(project.path()), baseline_index);
        assert_eq!(
            std::fs::read(project.path().join(".git/index")).unwrap(),
            baseline_index_bytes
        );
        match kind {
            IgnoredCollisionKind::TrackIgnoredFile => {
                assert_eq!(
                    std::fs::read(project.path().join("generated.txt")).unwrap(),
                    b"external ignored value\0with bytes\n"
                );
                assert_eq!(
                    std::fs::read_to_string(project.path().join(".gitignore")).unwrap(),
                    "generated.txt\n"
                );
            }
            IgnoredCollisionKind::ReplaceDirectory => {
                assert_eq!(
                    std::fs::read(project.path().join("shape/ignored.bin")).unwrap(),
                    b"external ignored child\0with bytes\n"
                );
                assert_eq!(
                    std::fs::read_to_string(project.path().join("shape/tracked.txt")).unwrap(),
                    "baseline tracked child\n"
                );
            }
        }
        assert!(git_output(project.path(), &["status", "--porcelain=v1"]).is_empty());
        assert_rollback_journal_empty(project.path());
        let _retained_run_commit = run_ref(project.path());
    }
}

#[tokio::test]
async fn ignored_file_created_after_collision_scan_is_quarantined_and_restored_byte_exact() {
    let project = initialized_project();
    std::fs::write(project.path().join(".gitignore"), "generated.txt\n").unwrap();
    commit_all(project.path(), "ignore generated race fixture");
    let baseline = head(project.path());
    let baseline_index = index_tree(project.path());
    let baseline_index_bytes = std::fs::read(project.path().join(".git/index")).unwrap();
    let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

    let failure = CodexWorkspaceAgent::new(Arc::new(IgnoredCollisionAdapter {
        kind: IgnoredCollisionKind::TrackIgnoredFile,
    }))
    .invoke(WorkspaceAgentInvocation {
        request_id: "ignored-after-collision-scan".into(),
        model: "test-model".into(),
        reasoning_effort: None,
        prompt: "Race an ignored file after collision scanning".into(),
        project_instructions: None,
        commit_subject: "Exercise atomic ignored quarantine".into(),
        cwd: project.path().to_path_buf(),
        baseline_commit: baseline.clone(),
        baseline_index_tree: baseline_index.clone(),
        cancellation: CancellationToken::new(),
        integration_gate: Some(Arc::new(TransactionInjectingGate {
            project: project.path().to_path_buf(),
            injection: TransactionInjection::IgnoredBeforeWorktreeMutation,
        })),
    })
    .await
    .unwrap_err();

    assert_eq!(failure.code, ait_domain::ErrorCode::ProjectGitDirty);
    assert_eq!(
        git_output(project.path(), &["rev-parse", &target_ref]),
        baseline
    );
    assert_eq!(index_tree(project.path()), baseline_index);
    assert_eq!(
        std::fs::read(project.path().join(".git/index")).unwrap(),
        baseline_index_bytes
    );
    assert_eq!(
        std::fs::read(project.path().join("generated.txt")).unwrap(),
        b"external ignored race\0with bytes\n"
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join(".gitignore")).unwrap(),
        "generated.txt\n"
    );
    assert_rollback_journal_empty(project.path());
    let _retained_run_commit = run_ref(project.path());
}

#[tokio::test]
async fn ignored_child_created_after_df_scan_is_restored_with_its_directory() {
    let project = initialized_project();
    std::fs::write(project.path().join(".gitignore"), "shape/ignored.bin\n").unwrap();
    std::fs::create_dir(project.path().join("shape")).unwrap();
    std::fs::write(
        project.path().join("shape/tracked.txt"),
        "baseline tracked child\n",
    )
    .unwrap();
    commit_all(project.path(), "add D/F ignored race fixture");
    let baseline = head(project.path());
    let baseline_index = index_tree(project.path());
    let baseline_index_bytes = std::fs::read(project.path().join(".git/index")).unwrap();
    let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

    let failure = CodexWorkspaceAgent::new(Arc::new(IgnoredCollisionAdapter {
        kind: IgnoredCollisionKind::ReplaceDirectory,
    }))
    .invoke(WorkspaceAgentInvocation {
        request_id: "ignored-df-after-collision-scan".into(),
        model: "test-model".into(),
        reasoning_effort: None,
        prompt: "Race an ignored D/F child after collision scanning".into(),
        project_instructions: None,
        commit_subject: "Exercise atomic D/F quarantine".into(),
        cwd: project.path().to_path_buf(),
        baseline_commit: baseline.clone(),
        baseline_index_tree: baseline_index.clone(),
        cancellation: CancellationToken::new(),
        integration_gate: Some(Arc::new(TransactionInjectingGate {
            project: project.path().to_path_buf(),
            injection: TransactionInjection::IgnoredBeforeWorktreeMutation,
        })),
    })
    .await
    .unwrap_err();

    assert_eq!(failure.code, ait_domain::ErrorCode::ProjectGitDirty);
    assert_eq!(
        git_output(project.path(), &["rev-parse", &target_ref]),
        baseline
    );
    assert_eq!(index_tree(project.path()), baseline_index);
    assert_eq!(
        std::fs::read(project.path().join(".git/index")).unwrap(),
        baseline_index_bytes
    );
    assert_eq!(
        std::fs::read(project.path().join("shape/ignored.bin")).unwrap(),
        b"external ignored race\0with bytes\n"
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join("shape/tracked.txt")).unwrap(),
        "baseline tracked child\n"
    );
    assert_rollback_journal_empty(project.path());
    let _retained_run_commit = run_ref(project.path());
}

#[tokio::test]
async fn rollback_atomically_isolates_live_file_or_directory_before_candidate_validation() {
    for injection in [
        TransactionInjection::SamePathBeforeRollback,
        TransactionInjection::DirectoryBeforeRollback,
    ] {
        let project = initialized_project();
        std::fs::write(project.path().join("tracked.txt"), "authorized baseline\n").unwrap();
        commit_all(project.path(), "add rollback isolation fixture");
        let baseline = head(project.path());
        let baseline_index = index_tree(project.path());
        let baseline_index_bytes = std::fs::read(project.path().join(".git/index")).unwrap();
        let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

        let failure = CodexWorkspaceAgent::new(Arc::new(TransactionEditingAdapter))
            .invoke(WorkspaceAgentInvocation {
                request_id: format!("atomic-rollback-isolation-{injection:?}"),
                model: "test-model".into(),
                reasoning_effort: None,
                prompt: "Race a live path before rollback isolation".into(),
                project_instructions: None,
                commit_subject: "Exercise atomic rollback isolation".into(),
                cwd: project.path().to_path_buf(),
                baseline_commit: baseline.clone(),
                baseline_index_tree: baseline_index.clone(),
                cancellation: CancellationToken::new(),
                integration_gate: Some(Arc::new(TransactionInjectingGate {
                    project: project.path().to_path_buf(),
                    injection,
                })),
            })
            .await
            .unwrap_err();

        assert_eq!(
            failure.code,
            ait_domain::ErrorCode::RunRecoveryFailed,
            "injection: {injection:?}: {}",
            failure.message
        );
        assert_eq!(
            git_output(project.path(), &["rev-parse", &target_ref]),
            baseline
        );
        assert_eq!(index_tree(project.path()), baseline_index);
        assert_eq!(
            std::fs::read(project.path().join(".git/index")).unwrap(),
            baseline_index_bytes
        );
        match injection {
            TransactionInjection::SamePathBeforeRollback => assert_eq!(
                std::fs::read_to_string(project.path().join("tracked.txt")).unwrap(),
                "external value before rollback isolation\n"
            ),
            TransactionInjection::DirectoryBeforeRollback => assert_eq!(
                std::fs::read(project.path().join("tracked.txt/external.bin")).unwrap(),
                b"external directory race\0with bytes\n"
            ),
            _ => unreachable!(),
        }
        assert!(!project.path().join("run-owned.txt").exists());
        assert_rollback_journal_retained(project.path());
        let _retained_run_commit = run_ref(project.path());
    }
}

#[tokio::test]
async fn baseline_ref_reconciliation_locks_before_confirming_the_noop() {
    let project = initialized_project();
    std::fs::write(project.path().join("tracked.txt"), "authorized baseline\n").unwrap();
    commit_all(project.path(), "add baseline ref race fixture");
    let baseline = head(project.path());
    let external = git_output(project.path(), &["rev-parse", &format!("{baseline}^")]);
    let baseline_index = index_tree(project.path());
    let baseline_index_bytes = std::fs::read(project.path().join(".git/index")).unwrap();
    let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

    let failure = CodexWorkspaceAgent::new(Arc::new(TransactionEditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "baseline-ref-reconciliation-lock".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Race the baseline ref reconciliation lock".into(),
            project_instructions: None,
            commit_subject: "Exercise baseline ref reconciliation lock".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: baseline.clone(),
            baseline_index_tree: baseline_index.clone(),
            cancellation: CancellationToken::new(),
            integration_gate: Some(Arc::new(TransactionInjectingGate {
                project: project.path().to_path_buf(),
                injection: TransactionInjection::BaselineRefAdvanceBeforeLock,
            })),
        })
        .await
        .unwrap_err();

    assert_eq!(
        failure.code,
        ait_domain::ErrorCode::RunRecoveryFailed,
        "{}",
        failure.message
    );
    assert_eq!(
        git_output(project.path(), &["rev-parse", &target_ref]),
        external
    );
    let symbolic_target = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["symbolic-ref", &target_ref])
        .output()
        .unwrap();
    assert!(!symbolic_target.status.success());
    assert_eq!(index_tree(project.path()), baseline_index);
    assert_eq!(
        std::fs::read(project.path().join(".git/index")).unwrap(),
        baseline_index_bytes
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join("tracked.txt")).unwrap(),
        "authorized baseline\n"
    );
    assert!(!project.path().join("run-owned.txt").exists());
    assert_rollback_journal_empty(project.path());
    let _retained_run_commit = run_ref(project.path());
}

#[tokio::test]
async fn rollback_classifies_filter_owned_files_before_removing_gitattributes() {
    let project = initialized_project();
    std::fs::write(project.path().join(".gitattributes"), "data.txt -ident\n").unwrap();
    std::fs::write(project.path().join("data.txt"), "baseline data\n").unwrap();
    commit_all(project.path(), "add attribute rollback fixture");
    let baseline = head(project.path());
    let baseline_index = index_tree(project.path());
    let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

    let failure = CodexWorkspaceAgent::new(Arc::new(AttributeEditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "attribute-sensitive-rollback".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Change attributes and an affected file".into(),
            project_instructions: None,
            commit_subject: "Exercise attribute-sensitive rollback".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: baseline.clone(),
            baseline_index_tree: baseline_index.clone(),
            cancellation: CancellationToken::new(),
            integration_gate: Some(Arc::new(TransactionInjectingGate {
                project: project.path().to_path_buf(),
                injection: TransactionInjection::FailureAfterRefPublish,
            })),
        })
        .await
        .unwrap_err();

    assert_eq!(
        failure.code,
        ait_domain::ErrorCode::ProjectGitHeadUnavailable,
        "{}",
        failure.message
    );
    assert_eq!(
        git_output(project.path(), &["rev-parse", &target_ref]),
        baseline
    );
    assert_eq!(index_tree(project.path()), baseline_index);
    assert_eq!(
        std::fs::read_to_string(project.path().join(".gitattributes")).unwrap(),
        "data.txt -ident\n"
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join("data.txt")).unwrap(),
        "baseline data\n"
    );
    assert!(git_output(project.path(), &["status", "--porcelain=v1"]).is_empty());
    assert_rollback_journal_empty(project.path());
    let _retained_run_commit = run_ref(project.path());
}

#[tokio::test]
async fn rollback_preserves_a_target_ref_replaced_by_a_candidate_resolving_symref() {
    let project = initialized_project();
    std::fs::write(project.path().join("tracked.txt"), "authorized baseline\n").unwrap();
    commit_all(project.path(), "add ref identity fixture");
    let baseline = head(project.path());
    let baseline_index = index_tree(project.path());
    let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

    let failure = CodexWorkspaceAgent::new(Arc::new(TransactionEditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "target-ref-symref-identity".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Exercise target ref identity preservation".into(),
            project_instructions: None,
            commit_subject: "Exercise target identity rollback".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: baseline.clone(),
            baseline_index_tree: baseline_index.clone(),
            cancellation: CancellationToken::new(),
            integration_gate: Some(Arc::new(TransactionInjectingGate {
                project: project.path().to_path_buf(),
                injection: TransactionInjection::TargetSymrefAfterRefPublish,
            })),
        })
        .await
        .unwrap_err();

    assert_eq!(
        failure.code,
        ait_domain::ErrorCode::RunRecoveryFailed,
        "{}",
        failure.message
    );
    assert_eq!(
        git_output(project.path(), &["symbolic-ref", &target_ref]),
        "refs/heads/injected-ref-target"
    );
    let retained_run_ref = run_ref(project.path());
    assert_eq!(
        git_output(
            project.path(),
            &["rev-parse", "refs/heads/injected-ref-target"]
        ),
        git_output(project.path(), &["rev-parse", &retained_run_ref])
    );
    assert_eq!(index_tree(project.path()), baseline_index);
    assert_eq!(
        std::fs::read_to_string(project.path().join("tracked.txt")).unwrap(),
        "authorized baseline\n"
    );
    assert!(!project.path().join("run-owned.txt").exists());
    assert_rollback_journal_empty(project.path());
}

#[tokio::test]
async fn directory_file_transitions_roll_back_ref_index_and_worktree_after_publication() {
    for direction in [
        DirectoryFileDirection::FileToDirectory,
        DirectoryFileDirection::DirectoryToFile,
    ] {
        let project = initialized_project();
        match direction {
            DirectoryFileDirection::FileToDirectory => {
                std::fs::write(project.path().join("shape"), "baseline file\n").unwrap();
            }
            DirectoryFileDirection::DirectoryToFile => {
                std::fs::create_dir(project.path().join("shape")).unwrap();
                std::fs::write(
                    project.path().join("shape/child.txt"),
                    "baseline directory child\n",
                )
                .unwrap();
                std::fs::write(
                    project.path().join("shape/sibling.txt"),
                    "baseline directory sibling\n",
                )
                .unwrap();
            }
        }
        commit_all(project.path(), "add D/F baseline");
        let baseline = head(project.path());
        let baseline_index = index_tree(project.path());
        let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);

        let failure = CodexWorkspaceAgent::new(Arc::new(DirectoryFileEditingAdapter { direction }))
            .invoke(WorkspaceAgentInvocation {
                request_id: format!("directory-file-{direction:?}"),
                model: "test-model".into(),
                reasoning_effort: None,
                prompt: "Exercise a D/F transition".into(),
                project_instructions: None,
                commit_subject: "Exercise D/F rollback".into(),
                cwd: project.path().to_path_buf(),
                baseline_commit: baseline.clone(),
                baseline_index_tree: baseline_index.clone(),
                cancellation: CancellationToken::new(),
                integration_gate: Some(Arc::new(TransactionInjectingGate {
                    project: project.path().to_path_buf(),
                    injection: TransactionInjection::FailureAfterRefPublish,
                })),
            })
            .await
            .unwrap_err();

        assert_eq!(
            failure.code,
            ait_domain::ErrorCode::ProjectGitHeadUnavailable,
            "direction: {direction:?}: {}",
            failure.message
        );
        assert_eq!(
            git_output(project.path(), &["rev-parse", &target_ref]),
            baseline,
            "target ref changed for {direction:?}"
        );
        assert_eq!(index_tree(project.path()), baseline_index);
        match direction {
            DirectoryFileDirection::FileToDirectory => {
                assert_eq!(
                    std::fs::read_to_string(project.path().join("shape")).unwrap(),
                    "baseline file\n"
                );
            }
            DirectoryFileDirection::DirectoryToFile => {
                assert_eq!(
                    std::fs::read_to_string(project.path().join("shape/child.txt")).unwrap(),
                    "baseline directory child\n"
                );
                assert_eq!(
                    std::fs::read_to_string(project.path().join("shape/sibling.txt")).unwrap(),
                    "baseline directory sibling\n"
                );
            }
        }
        assert!(git_output(project.path(), &["status", "--porcelain=v1"]).is_empty());
        assert_rollback_journal_empty(project.path());
        let _retained_run_commit = run_ref(project.path());
    }
}

#[tokio::test]
async fn detached_head_rollback_preserves_a_later_symbolic_head() {
    let project = initialized_project();
    std::fs::write(project.path().join("tracked.txt"), "authorized baseline\n").unwrap();
    commit_all(project.path(), "add detached rollback fixture");
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args(["switch", "--detach"])
            .status()
            .unwrap()
            .success()
    );
    let baseline = head(project.path());
    let baseline_index = index_tree(project.path());

    let failure = CodexWorkspaceAgent::new(Arc::new(TransactionEditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "detached-head-ref-identity".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Exercise detached HEAD rollback".into(),
            project_instructions: None,
            commit_subject: "Exercise detached rollback".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: baseline.clone(),
            baseline_index_tree: baseline_index.clone(),
            cancellation: CancellationToken::new(),
            integration_gate: Some(Arc::new(TransactionInjectingGate {
                project: project.path().to_path_buf(),
                injection: TransactionInjection::BranchSwitchAfterRefPublish,
            })),
        })
        .await
        .unwrap_err();

    assert_eq!(failure.code, ait_domain::ErrorCode::RunRecoveryFailed);
    assert_eq!(
        git_output(project.path(), &["symbolic-ref", "HEAD"]),
        "refs/heads/injected-after-publication"
    );
    assert_eq!(head(project.path()), baseline);
    assert_eq!(index_tree(project.path()), baseline_index);
    assert_eq!(
        std::fs::read_to_string(project.path().join("tracked.txt")).unwrap(),
        "external branch-switch value\n"
    );
    assert!(!project.path().join("run-owned.txt").exists());
    let _retained_run_commit = run_ref(project.path());
}

fn assert_rollback_journal_empty(project: &Path) {
    let rollback_root = project.join(".git/ait/integration-rollbacks");
    assert!(
        !rollback_root.exists() || std::fs::read_dir(rollback_root).unwrap().next().is_none(),
        "rollback material leaked"
    );
}

fn assert_rollback_journal_retained(project: &Path) {
    let rollback_root = project.join(".git/ait/integration-rollbacks");
    assert!(
        rollback_root.exists() && std::fs::read_dir(rollback_root).unwrap().next().is_some(),
        "rollback recovery material was discarded"
    );
}

#[cfg(unix)]
#[tokio::test]
async fn controlled_worktree_setup_skips_successful_and_failing_post_checkout_hooks() {
    use std::os::unix::fs::PermissionsExt as _;

    for exit_code in [0, 1] {
        let project = initialized_project();
        let marker = project.path().join(format!("hook-ran-{exit_code}"));
        let hook = project.path().join(".git/hooks/post-checkout");
        std::fs::write(
            &hook,
            format!(
                "#!/bin/sh\nprintf hook-side-effect > '{}'\nexit {exit_code}\n",
                marker.display()
            ),
        )
        .unwrap();
        let mut permissions = std::fs::metadata(&hook).unwrap().permissions();
        permissions.set_mode(0o755);
        std::fs::set_permissions(&hook, permissions).unwrap();

        let result = CodexWorkspaceAgent::new(Arc::new(EditingAdapter))
            .invoke(WorkspaceAgentInvocation {
                request_id: format!("hook-{exit_code}"),
                model: "test-model".into(),
                reasoning_effort: None,
                prompt: "Create answer.txt".into(),
                project_instructions: Some("Keep generated files small.".into()),
                commit_subject: "Create answer.txt".into(),
                cwd: project.path().to_path_buf(),
                baseline_commit: head(project.path()),
                baseline_index_tree: index_tree(project.path()),
                cancellation: CancellationToken::new(),
                integration_gate: None,
            })
            .await
            .unwrap();

        assert!(result.commit_id.is_some());
        assert!(!marker.exists(), "post-checkout ran with exit {exit_code}");
        assert!(git_output(project.path(), &["for-each-ref", "refs/ait/runs"]).is_empty());
        assert_eq!(
            git_output(project.path(), &["worktree", "list", "--porcelain"])
                .lines()
                .filter(|line| line.starts_with("worktree "))
                .count(),
            1
        );
    }
}

#[tokio::test]
async fn successful_runs_rewrite_absolute_workspace_paths_before_cleanup() {
    let project = initialized_project();
    let result = CodexWorkspaceAgent::new(Arc::new(AbsolutePathAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "absolute-paths".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Report paths".into(),
            project_instructions: None,
            commit_subject: "Report paths".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap();

    assert_eq!(result.operations.len(), 3);
    assert_eq!(result.operations[0].paths, ["."]);
    assert_eq!(result.operations[1].paths, ["answer.txt"]);
    assert_eq!(result.operations[2].paths, ["preview.png"]);
    assert!(
        result
            .operations
            .iter()
            .flat_map(|item| &item.paths)
            .all(|path| {
                !Path::new(path).is_absolute() && !path.contains(".git/ait/workspaces")
            })
    );
}

#[tokio::test]
async fn initialized_submodules_are_rejected_with_an_actionable_error() {
    let module = initialized_project();
    std::fs::write(module.path().join("module.txt"), "module content\n").unwrap();
    commit_all(module.path(), "add module content");
    let project = initialized_project();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args([
                "-c",
                "protocol.file.allow=always",
                "submodule",
                "add",
                module.path().to_str().unwrap(),
                "module",
            ])
            .status()
            .unwrap()
            .success()
    );
    commit_all(project.path(), "add initialized submodule");

    let failure = CodexWorkspaceAgent::new(Arc::new(EditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "initialized-submodule".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Inspect the module".into(),
            project_instructions: Some("Keep generated files small.".into()),
            commit_subject: "Inspect the module".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap_err();

    assert_eq!(failure.code, ait_domain::ErrorCode::InvalidConfiguration);
    assert!(failure.message.contains("deinitialize"));
    let submodule_status = git_output(project.path(), &["submodule", "status", "--recursive"]);
    assert!(!submodule_status.starts_with('-'));
    assert!(submodule_status.contains(" module"));
    assert!(git_output(project.path(), &["status", "--porcelain=v1"]).is_empty());
}
