//! Workspace execution and Git commit coverage for the Codex adapter.

use std::{
    path::{Path, PathBuf},
    process::Command,
    sync::Arc,
};

use ait_agent_adapters::{
    AdapterError, AgentAdapter, AgentCapabilities, AgentEvent, AgentRunRequest, AgentRunStatus,
    AgentStream, SandboxMode,
    codex::{CodexSessionTitleGenerator, CodexWorkspaceAgent},
};
use ait_ports::{
    SessionTitleGenerator, SessionTitleRequest, WorkspaceAgent, WorkspaceAgentInvocation,
    WorkspaceIntegrationGate, WorkspaceOutputItem,
};
use async_trait::async_trait;
use serde_json::json;
use tempfile::TempDir;
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;

#[derive(Debug)]
struct EditingAdapter;

#[async_trait]
impl AgentAdapter for EditingAdapter {
    fn driver(&self) -> &'static str {
        "editing_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        assert_eq!(
            request.project_instructions.as_deref(),
            Some("Keep generated files small.")
        );
        std::fs::write(request.cwd.join("answer.txt"), "generated by codex\n").unwrap();
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemStarted {
                item: json!({
                    "type": "agentMessage",
                    "id": "commentary-1",
                    "phase": "commentary",
                    "text": ""
                }),
            }),
            Ok(AgentEvent::MessageDelta {
                item_id: "commentary-1".into(),
                delta: "Inspecting the ".into(),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "commentary-1",
                    "phase": "commentary",
                    "text": "Inspecting the repository."
                }),
            }),
            Ok(AgentEvent::ItemStarted {
                item: json!({
                    "type": "commandExecution",
                    "id": "command-1",
                    "status": "inProgress"
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "commandExecution",
                    "id": "command-1",
                    "command": "sed -n '1,20p' src/main.rs",
                    "cwd": "/workspace",
                    "status": "completed",
                    "commandActions": [{
                        "type": "read",
                        "command": "sed -n '1,20p' src/main.rs",
                        "name": "main.rs",
                        "path": "src/main.rs"
                    }],
                    "aggregatedOutput": "fn main() {}",
                    "exitCode": 0
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "commentary-2",
                    "phase": "commentary",
                    "text": "The relevant file is small."
                }),
            }),
            Ok(AgentEvent::ItemStarted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-1",
                    "phase": "final_answer",
                    "text": ""
                }),
            }),
            Ok(AgentEvent::MessageDelta {
                item_id: "final-1".into(),
                delta: "Implemented the requested ".into(),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-1",
                    "phase": "final_answer",
                    "text": "Implemented the requested change."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-1".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[derive(Debug)]
struct PausingEditingAdapter {
    entered: Semaphore,
    release: Semaphore,
}

#[derive(Clone, Copy, Debug)]
enum FinalValidationInjection {
    Branch,
    Staged,
    Unstaged,
    Untracked,
}

#[derive(Debug)]
struct InjectingIntegrationGate {
    project: PathBuf,
    injection: FinalValidationInjection,
}

#[async_trait]
impl WorkspaceIntegrationGate for InjectingIntegrationGate {
    async fn begin_integration(&self) -> Result<(), ait_domain::DomainError> {
        match self.injection {
            FinalValidationInjection::Branch => {
                assert!(
                    Command::new("git")
                        .arg("-C")
                        .arg(&self.project)
                        .args(["switch", "injected-branch"])
                        .status()
                        .unwrap()
                        .success()
                );
            }
            FinalValidationInjection::Staged => {
                std::fs::write(self.project.join("staged.txt"), "external staged change\n")
                    .unwrap();
                assert!(
                    Command::new("git")
                        .arg("-C")
                        .arg(&self.project)
                        .args(["add", "staged.txt"])
                        .status()
                        .unwrap()
                        .success()
                );
            }
            FinalValidationInjection::Unstaged => {
                std::fs::write(
                    self.project.join("tracked.txt"),
                    "external unstaged change\n",
                )
                .unwrap();
            }
            FinalValidationInjection::Untracked => {
                std::fs::write(
                    self.project.join("untracked.txt"),
                    "external untracked change\n",
                )
                .unwrap();
            }
        }
        Ok(())
    }
}

#[derive(Debug)]
struct AbsolutePathAdapter;

#[async_trait]
impl AgentAdapter for AbsolutePathAdapter {
    fn driver(&self) -> &'static str {
        "absolute_path_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        let root = request.cwd.display().to_string();
        let answer = request.cwd.join("answer.txt").display().to_string();
        let image = request.cwd.join("preview.png").display().to_string();
        std::fs::write(&answer, "generated\n").unwrap();
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "commandExecution",
                    "id": "absolute-cwd",
                    "status": "completed",
                    "commandActions": [{"type": "listFiles", "cwd": root}]
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "fileChange",
                    "id": "absolute-file",
                    "status": "completed",
                    "changes": [{"path": answer, "kind": "add"}]
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "imageView",
                    "id": "absolute-image",
                    "status": "completed",
                    "path": image
                }),
            }),
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-paths",
                    "phase": "final_answer",
                    "text": "Recorded paths."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-paths".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

impl PausingEditingAdapter {
    fn new() -> Self {
        Self {
            entered: Semaphore::new(0),
            release: Semaphore::new(0),
        }
    }

    async fn started(&self) {
        self.entered.acquire().await.unwrap().forget();
    }
}

#[async_trait]
impl AgentAdapter for PausingEditingAdapter {
    fn driver(&self) -> &'static str {
        "pausing_editing_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: true,
            file_changes: true,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        std::fs::write(request.cwd.join("agent-owned.txt"), "agent change\n").unwrap();
        self.entered.add_permits(1);
        tokio::select! {
            permit = self.release.acquire() => permit.unwrap().forget(),
            () = request.cancellation.cancelled() => return Err(AdapterError::cancelled()),
        }
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::ItemCompleted {
                item: json!({
                    "type": "agentMessage",
                    "id": "final-paused",
                    "phase": "final_answer",
                    "text": "Finished isolated edit."
                }),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-paused".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[derive(Debug)]
struct TitleAdapter;

#[async_trait]
impl AgentAdapter for TitleAdapter {
    fn driver(&self) -> &'static str {
        "title_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: false,
            file_changes: false,
            usage: false,
        }
    }

    async fn run(&self, request: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        assert_eq!(request.model.as_deref(), Some("gpt-5.6-luna"));
        assert_eq!(request.reasoning_effort.as_deref(), Some("low"));
        assert_eq!(request.sandbox, SandboxMode::ReadOnly);
        assert_eq!(
            request.output_schema.as_ref().unwrap()["required"][0],
            "title"
        );
        assert!(request.prompt.contains("ABC-123"));
        Ok(Box::pin(tokio_stream::iter([
            Ok(AgentEvent::MessageDelta {
                item_id: "message-title".into(),
                delta: r#"{"title":"修复 ABC-123 登录","description":"修复登录流程中的工单问题"}"#
                    .into(),
            }),
            Ok(AgentEvent::Completed {
                turn_id: "turn-title".into(),
                status: AgentRunStatus::Completed,
                error: None,
            }),
        ])))
    }
}

#[derive(Debug)]
struct ScriptedAdapter {
    events: Vec<AgentEvent>,
}

#[async_trait]
impl AgentAdapter for ScriptedAdapter {
    fn driver(&self) -> &'static str {
        "scripted_test"
    }

    fn capabilities(&self) -> AgentCapabilities {
        AgentCapabilities {
            streaming: true,
            thread_resume: false,
            approvals: false,
            command_execution: false,
            file_changes: false,
            usage: false,
        }
    }

    async fn run(&self, _: AgentRunRequest) -> Result<AgentStream, AdapterError> {
        Ok(Box::pin(tokio_stream::iter(
            self.events.clone().into_iter().map(Ok),
        )))
    }
}

fn initialized_project() -> TempDir {
    let project = TempDir::new().unwrap();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .arg("init")
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args([
                "-c",
                "user.name=Test",
                "-c",
                "user.email=test@example.invalid",
                "commit",
                "--allow-empty",
                "-m",
                "initial",
            ])
            .status()
            .unwrap()
            .success()
    );
    project
}

fn head(project: &Path) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .args(["rev-parse", "HEAD"])
        .output()
        .unwrap();
    String::from_utf8(output.stdout).unwrap().trim().to_owned()
}

fn index_tree(project: &Path) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .arg("write-tree")
        .output()
        .unwrap();
    assert!(output.status.success());
    String::from_utf8(output.stdout).unwrap().trim().to_owned()
}

fn git_output(project: &Path, arguments: &[&str]) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .args(arguments)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "git {arguments:?}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).unwrap().trim().to_owned()
}

fn commit_all(project: &Path, subject: &str) {
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project)
            .args(["add", "--all"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project)
            .args([
                "-c",
                "user.name=Test",
                "-c",
                "user.email=test@example.invalid",
                "commit",
                "-m",
                subject,
            ])
            .status()
            .unwrap()
            .success()
    );
}

fn run_ref(project: &Path) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(project)
        .args(["for-each-ref", "--format=%(refname)", "refs/ait/runs"])
        .output()
        .unwrap();
    let references = String::from_utf8(output.stdout).unwrap();
    let references = references.lines().collect::<Vec<_>>();
    assert_eq!(references.len(), 1);
    references[0].to_owned()
}

fn paused_request(project: &Path, request_id: &str) -> WorkspaceAgentInvocation {
    WorkspaceAgentInvocation {
        request_id: request_id.into(),
        model: "test-model".into(),
        reasoning_effort: None,
        prompt: "Make an isolated edit".into(),
        project_instructions: None,
        commit_subject: "Make an isolated edit".into(),
        cwd: project.to_path_buf(),
        baseline_commit: head(project),
        baseline_index_tree: index_tree(project),
        cancellation: CancellationToken::new(),
        integration_gate: None,
    }
}

async fn invoke_script(events: Vec<AgentEvent>) -> ait_ports::WorkspaceAgentResponse {
    let project = initialized_project();
    CodexWorkspaceAgent::new(Arc::new(ScriptedAdapter { events }))
        .invoke(WorkspaceAgentInvocation {
            request_id: "scripted-run".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Return a result".into(),
            project_instructions: None,
            commit_subject: "Return a result".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap()
}

#[tokio::test]
async fn generates_structured_session_metadata_with_the_small_read_only_model() {
    let project = TempDir::new().unwrap();
    let generator = CodexSessionTitleGenerator::new(Arc::new(TitleAdapter));
    let generated = generator
        .generate(SessionTitleRequest {
            request_id: "title-1".into(),
            user_prompt: "修复 ABC-123 登录".into(),
            cwd: project.path().to_path_buf(),
            cancellation: CancellationToken::new(),
        })
        .await
        .unwrap();

    assert_eq!(generated.title, "修复 ABC-123 登录");
    assert_eq!(generated.description, "修复登录流程中的工单问题");
}

#[tokio::test]
async fn returns_assistant_result_and_commits_generated_changes() {
    let project = initialized_project();
    let agent = CodexWorkspaceAgent::new(Arc::new(EditingAdapter));
    let result = agent
        .invoke(WorkspaceAgentInvocation {
            request_id: "run-1".into(),
            model: "test-model".into(),
            reasoning_effort: Some("high".into()),
            prompt: "Create answer.txt".into(),
            project_instructions: Some("Keep generated files small.".into()),
            commit_subject: "Create the generated answer".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap();

    assert_eq!(result.assistant_text, "Implemented the requested change.");
    assert!(result.commit_id.is_some());
    assert_eq!(result.operations.len(), 1);
    assert_eq!(result.operations[0].kind, "read");
    assert_eq!(result.operations[0].title, "Read file");
    assert_eq!(result.operations[0].paths, ["src/main.rs"]);
    assert!(
        result.operations[0]
            .detail
            .as_deref()
            .unwrap()
            .contains("fn main() {}")
    );
    assert_eq!(
        result.output_items,
        [
            WorkspaceOutputItem::Message {
                id: "commentary-1".into(),
                phase: Some("commentary".into()),
                text: "Inspecting the repository.".into(),
            },
            WorkspaceOutputItem::Operation {
                id: "command-1".into(),
            },
            WorkspaceOutputItem::Message {
                id: "commentary-2".into(),
                phase: Some("commentary".into()),
                text: "The relevant file is small.".into(),
            },
            WorkspaceOutputItem::Message {
                id: "final-1".into(),
                phase: Some("final_answer".into()),
                text: "Implemented the requested change.".into(),
            },
        ]
    );
    let subject = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["log", "-1", "--pretty=%s"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8_lossy(&subject.stdout).trim(),
        "ait: Create the generated answer"
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join("answer.txt")).unwrap(),
        "generated by codex\n"
    );
    let status = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["status", "--porcelain=v1"])
        .output()
        .unwrap();
    assert!(status.stdout.is_empty());
    let worktrees = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["worktree", "list", "--porcelain"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(worktrees.stdout)
            .unwrap()
            .lines()
            .filter(|line| line.starts_with("worktree "))
            .count(),
        1
    );
    let refs = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["for-each-ref", "refs/ait/runs"])
        .output()
        .unwrap();
    assert!(refs.stdout.is_empty());
}

#[tokio::test]
async fn detached_primary_head_advances_without_moving_the_original_branch() {
    let project = initialized_project();
    let branch = git_output(project.path(), &["symbolic-ref", "HEAD"]);
    let baseline = head(project.path());
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args(["checkout", "--detach"])
            .status()
            .unwrap()
            .success()
    );

    let result = CodexWorkspaceAgent::new(Arc::new(EditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "detached-head".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Create answer.txt".into(),
            project_instructions: Some("Keep generated files small.".into()),
            commit_subject: "Create answer.txt".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: baseline.clone(),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap();

    assert_eq!(head(project.path()), result.commit_id.unwrap());
    assert_eq!(
        git_output(project.path(), &["rev-parse", &branch]),
        baseline
    );
    let symbolic = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["symbolic-ref", "--quiet", "HEAD"])
        .status()
        .unwrap();
    assert_eq!(symbolic.code(), Some(1));
}

#[tokio::test]
async fn retains_completed_only_final_text_and_does_not_repeat_completed_delta_text() {
    let completed_only = invoke_script(vec![
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "final-completed-only",
                "phase": "final_answer",
                "text": "Complete final answer."
            }),
        },
        AgentEvent::Completed {
            turn_id: "turn-completed-only".into(),
            status: AgentRunStatus::Completed,
            error: None,
        },
    ])
    .await;
    assert_eq!(completed_only.assistant_text, "Complete final answer.");
    assert_eq!(
        completed_only.output_items,
        [WorkspaceOutputItem::Message {
            id: "final-completed-only".into(),
            phase: Some("final_answer".into()),
            text: "Complete final answer.".into(),
        }]
    );

    let delta_and_completed = invoke_script(vec![
        AgentEvent::MessageDelta {
            item_id: "final-with-delta".into(),
            delta: "Complete ".into(),
        },
        AgentEvent::MessageDelta {
            item_id: "final-with-delta".into(),
            delta: "final answer.".into(),
        },
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "final-with-delta",
                "phase": "final_answer",
                "text": "Complete final answer."
            }),
        },
        AgentEvent::Completed {
            turn_id: "turn-with-delta".into(),
            status: AgentRunStatus::Completed,
            error: None,
        },
    ])
    .await;
    assert_eq!(delta_and_completed.assistant_text, "Complete final answer.");
    assert_eq!(
        delta_and_completed.output_items,
        [WorkspaceOutputItem::Message {
            id: "final-with-delta".into(),
            phase: Some("final_answer".into()),
            text: "Complete final answer.".into(),
        }]
    );
}

#[tokio::test]
async fn keeps_messages_from_legacy_streams_without_phase() {
    let result = invoke_script(vec![
        AgentEvent::MessageDelta {
            item_id: "legacy-progress".into(),
            delta: "Legacy progress".into(),
        },
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "legacy-progress",
                "text": "Legacy progress message."
            }),
        },
        AgentEvent::ItemCompleted {
            item: json!({
                "type": "agentMessage",
                "id": "legacy-final",
                "text": "Legacy final answer."
            }),
        },
        AgentEvent::Completed {
            turn_id: "legacy-turn".into(),
            status: AgentRunStatus::Completed,
            error: None,
        },
    ])
    .await;

    assert_eq!(result.assistant_text, "Legacy final answer.");
    assert_eq!(
        result.output_items,
        [
            WorkspaceOutputItem::Message {
                id: "legacy-progress".into(),
                phase: None,
                text: "Legacy progress message.".into(),
            },
            WorkspaceOutputItem::Message {
                id: "legacy-final".into(),
                phase: None,
                text: "Legacy final answer.".into(),
            },
        ]
    );
}

#[tokio::test]
async fn refuses_to_mix_existing_user_changes_into_codex_commit() {
    let project = initialized_project();
    std::fs::write(project.path().join("user-work.txt"), "keep me\n").unwrap();
    let agent = CodexWorkspaceAgent::new(Arc::new(EditingAdapter));
    let error = agent
        .invoke(WorkspaceAgentInvocation {
            request_id: "run-2".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Change something".into(),
            project_instructions: None,
            commit_subject: "Change something".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap_err();

    assert_eq!(error.code, ait_domain::ErrorCode::ProjectGitDirty);
    assert!(!project.path().join("answer.txt").exists());
}

#[tokio::test]
async fn running_user_edit_is_not_mixed_and_the_agent_commit_is_retained() {
    let project = initialized_project();
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "user-edit-race");
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    assert!(!project.path().join("agent-owned.txt").exists());
    std::fs::write(project.path().join("user-owned.txt"), "user change\n").unwrap();
    adapter.release.add_permits(1);

    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(failure.code, ait_domain::ErrorCode::ProjectGitDirty);
    assert!(
        failure
            .message
            .contains("isolated Run changes were retained")
    );
    assert_eq!(
        std::fs::read_to_string(project.path().join("user-owned.txt")).unwrap(),
        "user change\n"
    );
    assert!(!project.path().join("agent-owned.txt").exists());
    let reference = run_ref(project.path());
    let changed = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["show", "--pretty=format:", "--name-only", &reference])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(changed.stdout).unwrap().trim(),
        "agent-owned.txt"
    );
}

#[tokio::test]
async fn head_advance_rejects_integration_without_overwriting_either_change() {
    let project = initialized_project();
    let baseline = head(project.path());
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "head-race");
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    std::fs::write(project.path().join("external.txt"), "external commit\n").unwrap();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args(["add", "external.txt"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args([
                "-c",
                "user.name=External",
                "-c",
                "user.email=external@example.invalid",
                "commit",
                "-m",
                "external",
            ])
            .status()
            .unwrap()
            .success()
    );
    adapter.release.add_permits(1);

    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(
        failure.code,
        ait_domain::ErrorCode::ProjectGitHeadUnavailable
    );
    assert_ne!(head(project.path()), baseline);
    assert!(!project.path().join("agent-owned.txt").exists());
    let reference = run_ref(project.path());
    let merge_base = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["merge-base", &reference, "HEAD"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(merge_base.stdout).unwrap().trim(),
        baseline
    );
}

#[tokio::test]
async fn index_change_rejects_integration_and_leaves_the_index_intact() {
    let project = initialized_project();
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "index-race");
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    std::fs::write(project.path().join("staged.txt"), "staged user change\n").unwrap();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args(["add", "staged.txt"])
            .status()
            .unwrap()
            .success()
    );
    adapter.release.add_permits(1);

    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(failure.code, ait_domain::ErrorCode::ProjectGitDirty);
    let staged = Command::new("git")
        .arg("-C")
        .arg(project.path())
        .args(["diff", "--cached", "--name-only"])
        .output()
        .unwrap();
    assert_eq!(
        String::from_utf8(staged.stdout).unwrap().trim(),
        "staged.txt"
    );
    assert!(!project.path().join("agent-owned.txt").exists());
    let _reference = run_ref(project.path());
}

#[tokio::test]
async fn cancellation_never_integrates_partial_changes_and_blocks_implicit_recovery() {
    let project = initialized_project();
    let adapter = Arc::new(PausingEditingAdapter::new());
    let agent = CodexWorkspaceAgent::new(adapter.clone());
    let request = paused_request(project.path(), "cancelled-race");
    let mut retry = request.clone();
    retry.cancellation = CancellationToken::new();
    let cancellation = request.cancellation.clone();
    let running = tokio::spawn(async move { agent.invoke(request).await });
    adapter.started().await;

    cancellation.cancel();
    let failure = running.await.unwrap().unwrap_err();
    assert_eq!(failure.code, ait_domain::ErrorCode::RunCancelled);
    assert!(
        failure
            .message
            .contains("isolated Run changes were retained")
    );
    assert!(!project.path().join("agent-owned.txt").exists());
    let _reference = run_ref(project.path());

    let retried = CodexWorkspaceAgent::new(adapter)
        .invoke(retry)
        .await
        .unwrap_err();
    assert_eq!(retried.code, ait_domain::ErrorCode::RunRecoveryFailed);
}

#[tokio::test]
async fn final_validation_injections_preserve_the_target_ref_and_external_changes() {
    for injection in [
        FinalValidationInjection::Branch,
        FinalValidationInjection::Staged,
        FinalValidationInjection::Unstaged,
        FinalValidationInjection::Untracked,
    ] {
        let project = initialized_project();
        std::fs::write(project.path().join("tracked.txt"), "authorized content\n").unwrap();
        commit_all(project.path(), "add tracked fixture");
        assert!(
            Command::new("git")
                .arg("-C")
                .arg(project.path())
                .args(["branch", "injected-branch"])
                .status()
                .unwrap()
                .success()
        );
        let baseline = head(project.path());
        let target_ref = git_output(project.path(), &["symbolic-ref", "HEAD"]);
        let adapter = Arc::new(PausingEditingAdapter::new());
        let agent = CodexWorkspaceAgent::new(adapter.clone());
        let mut request = paused_request(project.path(), &format!("final-{injection:?}"));
        request.integration_gate = Some(Arc::new(InjectingIntegrationGate {
            project: project.path().to_path_buf(),
            injection,
        }));
        let running = tokio::spawn(async move { agent.invoke(request).await });
        adapter.started().await;
        adapter.release.add_permits(1);

        let failure = running.await.unwrap().unwrap_err();
        let expected = if matches!(injection, FinalValidationInjection::Branch) {
            ait_domain::ErrorCode::ProjectGitHeadUnavailable
        } else {
            ait_domain::ErrorCode::ProjectGitDirty
        };
        assert_eq!(failure.code, expected, "injection: {injection:?}");
        assert_eq!(
            git_output(project.path(), &["rev-parse", &target_ref]),
            baseline,
            "the admitted target ref advanced for {injection:?}"
        );
        assert!(!project.path().join("agent-owned.txt").exists());
        match injection {
            FinalValidationInjection::Branch => {
                assert_eq!(
                    git_output(project.path(), &["symbolic-ref", "--short", "HEAD"]),
                    "injected-branch"
                );
            }
            FinalValidationInjection::Staged => {
                assert_eq!(
                    git_output(project.path(), &["diff", "--cached", "--name-only"]),
                    "staged.txt"
                );
            }
            FinalValidationInjection::Unstaged => {
                assert_eq!(
                    std::fs::read_to_string(project.path().join("tracked.txt")).unwrap(),
                    "external unstaged change\n"
                );
            }
            FinalValidationInjection::Untracked => {
                assert_eq!(
                    std::fs::read_to_string(project.path().join("untracked.txt")).unwrap(),
                    "external untracked change\n"
                );
            }
        }
        let _retained_agent_commit = run_ref(project.path());
    }
}

#[cfg(unix)]
#[tokio::test]
async fn controlled_worktree_setup_skips_successful_and_failing_post_checkout_hooks() {
    use std::os::unix::fs::PermissionsExt as _;

    for exit_code in [0, 1] {
        let project = initialized_project();
        let marker = project.path().join(format!("hook-ran-{exit_code}"));
        let hook = project.path().join(".git/hooks/post-checkout");
        std::fs::write(
            &hook,
            format!(
                "#!/bin/sh\nprintf hook-side-effect > '{}'\nexit {exit_code}\n",
                marker.display()
            ),
        )
        .unwrap();
        let mut permissions = std::fs::metadata(&hook).unwrap().permissions();
        permissions.set_mode(0o755);
        std::fs::set_permissions(&hook, permissions).unwrap();

        let result = CodexWorkspaceAgent::new(Arc::new(EditingAdapter))
            .invoke(WorkspaceAgentInvocation {
                request_id: format!("hook-{exit_code}"),
                model: "test-model".into(),
                reasoning_effort: None,
                prompt: "Create answer.txt".into(),
                project_instructions: Some("Keep generated files small.".into()),
                commit_subject: "Create answer.txt".into(),
                cwd: project.path().to_path_buf(),
                baseline_commit: head(project.path()),
                baseline_index_tree: index_tree(project.path()),
                cancellation: CancellationToken::new(),
                integration_gate: None,
            })
            .await
            .unwrap();

        assert!(result.commit_id.is_some());
        assert!(!marker.exists(), "post-checkout ran with exit {exit_code}");
        assert!(git_output(project.path(), &["for-each-ref", "refs/ait/runs"]).is_empty());
        assert_eq!(
            git_output(project.path(), &["worktree", "list", "--porcelain"])
                .lines()
                .filter(|line| line.starts_with("worktree "))
                .count(),
            1
        );
    }
}

#[tokio::test]
async fn successful_runs_rewrite_absolute_workspace_paths_before_cleanup() {
    let project = initialized_project();
    let result = CodexWorkspaceAgent::new(Arc::new(AbsolutePathAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "absolute-paths".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Report paths".into(),
            project_instructions: None,
            commit_subject: "Report paths".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap();

    assert_eq!(result.operations.len(), 3);
    assert_eq!(result.operations[0].paths, ["."]);
    assert_eq!(result.operations[1].paths, ["answer.txt"]);
    assert_eq!(result.operations[2].paths, ["preview.png"]);
    assert!(
        result
            .operations
            .iter()
            .flat_map(|item| &item.paths)
            .all(|path| {
                !Path::new(path).is_absolute() && !path.contains(".git/ait/workspaces")
            })
    );
}

#[tokio::test]
async fn initialized_submodules_are_rejected_with_an_actionable_error() {
    let module = initialized_project();
    std::fs::write(module.path().join("module.txt"), "module content\n").unwrap();
    commit_all(module.path(), "add module content");
    let project = initialized_project();
    assert!(
        Command::new("git")
            .arg("-C")
            .arg(project.path())
            .args([
                "-c",
                "protocol.file.allow=always",
                "submodule",
                "add",
                module.path().to_str().unwrap(),
                "module",
            ])
            .status()
            .unwrap()
            .success()
    );
    commit_all(project.path(), "add initialized submodule");

    let failure = CodexWorkspaceAgent::new(Arc::new(EditingAdapter))
        .invoke(WorkspaceAgentInvocation {
            request_id: "initialized-submodule".into(),
            model: "test-model".into(),
            reasoning_effort: None,
            prompt: "Inspect the module".into(),
            project_instructions: Some("Keep generated files small.".into()),
            commit_subject: "Inspect the module".into(),
            cwd: project.path().to_path_buf(),
            baseline_commit: head(project.path()),
            baseline_index_tree: index_tree(project.path()),
            cancellation: CancellationToken::new(),
            integration_gate: None,
        })
        .await
        .unwrap_err();

    assert_eq!(failure.code, ait_domain::ErrorCode::InvalidConfiguration);
    assert!(failure.message.contains("deinitialize"));
    let submodule_status = git_output(project.path(), &["submodule", "status", "--recursive"]);
    assert!(!submodule_status.starts_with('-'));
    assert!(submodule_status.contains(" module"));
    assert!(git_output(project.path(), &["status", "--porcelain=v1"]).is_empty());
}
