[package]
name = "server-model"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt", "sync", "time"] }
tokio-util = { version = "0.7.19", features = ["rt"] }

[lints]
workspace = true
