[package]
name = "ait-project-local"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ait-domain = { path = "../domain" }
ait-ports = { path = "../ports" }

[dev-dependencies]
ait-application = { path = "../application" }
tempfile = "3"

[lints]
workspace = true
